// ==============================================================
// Generated by Vitis HLS v2024.1.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ecg_classify_trained_ecg_classify_trained_Pipeline_VITIS_LOOP_73_68 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln71_8,
        tmp_114,
        hidden2,
        hidden2_1,
        hidden2_2,
        hidden2_3,
        hidden2_4,
        hidden2_5,
        hidden2_6,
        hidden2_7,
        hidden2_8,
        hidden2_9,
        hidden2_10,
        hidden2_11,
        hidden2_12,
        hidden2_13,
        hidden2_14,
        hidden2_15,
        hidden2_16,
        hidden2_17,
        hidden2_18,
        hidden2_19,
        hidden2_20,
        hidden2_21,
        hidden2_22,
        hidden2_23,
        hidden2_24,
        hidden2_25,
        hidden2_26,
        hidden2_27,
        hidden2_28,
        hidden2_29,
        hidden2_30,
        hidden2_31,
        hidden2_32,
        hidden2_33,
        hidden2_34,
        hidden2_35,
        hidden2_36,
        hidden2_37,
        hidden2_38,
        hidden2_39,
        hidden2_40,
        hidden2_41,
        hidden2_42,
        hidden2_43,
        hidden2_44,
        hidden2_45,
        hidden2_46,
        hidden2_47,
        hidden2_48,
        hidden2_49,
        hidden2_50,
        hidden2_51,
        hidden2_52,
        hidden2_53,
        hidden2_54,
        hidden2_55,
        hidden2_56,
        hidden2_57,
        hidden2_58,
        hidden2_59,
        hidden2_60,
        hidden2_61,
        hidden2_62,
        hidden2_63,
        sum_34_out,
        sum_34_out_ap_vld,
        dense_2_weights_address0,
        dense_2_weights_ce0,
        dense_2_weights_q0,
        grp_fu_13213_p_din0,
        grp_fu_13213_p_dout0,
        grp_fu_13213_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] sext_ln71_8;
input  [2:0] tmp_114;
input  [15:0] hidden2;
input  [15:0] hidden2_1;
input  [15:0] hidden2_2;
input  [15:0] hidden2_3;
input  [15:0] hidden2_4;
input  [15:0] hidden2_5;
input  [15:0] hidden2_6;
input  [15:0] hidden2_7;
input  [15:0] hidden2_8;
input  [15:0] hidden2_9;
input  [15:0] hidden2_10;
input  [15:0] hidden2_11;
input  [15:0] hidden2_12;
input  [15:0] hidden2_13;
input  [15:0] hidden2_14;
input  [15:0] hidden2_15;
input  [15:0] hidden2_16;
input  [15:0] hidden2_17;
input  [15:0] hidden2_18;
input  [15:0] hidden2_19;
input  [15:0] hidden2_20;
input  [15:0] hidden2_21;
input  [15:0] hidden2_22;
input  [15:0] hidden2_23;
input  [15:0] hidden2_24;
input  [15:0] hidden2_25;
input  [15:0] hidden2_26;
input  [15:0] hidden2_27;
input  [15:0] hidden2_28;
input  [15:0] hidden2_29;
input  [15:0] hidden2_30;
input  [15:0] hidden2_31;
input  [15:0] hidden2_32;
input  [15:0] hidden2_33;
input  [15:0] hidden2_34;
input  [15:0] hidden2_35;
input  [15:0] hidden2_36;
input  [15:0] hidden2_37;
input  [15:0] hidden2_38;
input  [15:0] hidden2_39;
input  [15:0] hidden2_40;
input  [15:0] hidden2_41;
input  [15:0] hidden2_42;
input  [15:0] hidden2_43;
input  [15:0] hidden2_44;
input  [15:0] hidden2_45;
input  [15:0] hidden2_46;
input  [15:0] hidden2_47;
input  [15:0] hidden2_48;
input  [15:0] hidden2_49;
input  [15:0] hidden2_50;
input  [15:0] hidden2_51;
input  [15:0] hidden2_52;
input  [15:0] hidden2_53;
input  [15:0] hidden2_54;
input  [15:0] hidden2_55;
input  [15:0] hidden2_56;
input  [15:0] hidden2_57;
input  [15:0] hidden2_58;
input  [15:0] hidden2_59;
input  [15:0] hidden2_60;
input  [15:0] hidden2_61;
input  [15:0] hidden2_62;
input  [15:0] hidden2_63;
output  [23:0] sum_34_out;
output   sum_34_out_ap_vld;
output  [10:0] dense_2_weights_address0;
output   dense_2_weights_ce0;
input  [31:0] dense_2_weights_q0;
output  [31:0] grp_fu_13213_p_din0;
input  [63:0] grp_fu_13213_p_dout0;
output   grp_fu_13213_p_ce;

reg ap_idle;
reg sum_34_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln73_fu_800_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln73_reg_1368;
reg   [0:0] icmp_ln73_reg_1368_pp0_iter1_reg;
reg   [0:0] icmp_ln73_reg_1368_pp0_iter2_reg;
reg   [0:0] icmp_ln73_reg_1368_pp0_iter3_reg;
reg   [0:0] icmp_ln73_reg_1368_pp0_iter4_reg;
reg   [0:0] icmp_ln73_reg_1368_pp0_iter5_reg;
reg   [0:0] icmp_ln73_reg_1368_pp0_iter6_reg;
reg   [0:0] icmp_ln73_reg_1368_pp0_iter7_reg;
wire   [15:0] tmp_16_fu_831_p131;
reg   [15:0] tmp_16_reg_1377;
reg   [15:0] tmp_16_reg_1377_pp0_iter1_reg;
reg   [15:0] tmp_16_reg_1377_pp0_iter2_reg;
reg   [15:0] tmp_16_reg_1377_pp0_iter3_reg;
reg   [15:0] tmp_16_reg_1377_pp0_iter4_reg;
reg  signed [15:0] tmp_16_reg_1377_pp0_iter5_reg;
reg   [31:0] dense_2_weights_load_reg_1382;
wire   [62:0] trunc_ln75_fu_1104_p1;
reg   [62:0] trunc_ln75_reg_1387;
reg   [0:0] tmp_reg_1392;
reg   [0:0] tmp_reg_1392_pp0_iter4_reg;
reg   [10:0] tmp_s_reg_1398;
wire   [51:0] trunc_ln75_6_fu_1126_p1;
reg   [51:0] trunc_ln75_6_reg_1403;
wire   [53:0] select_ln75_fu_1150_p3;
reg   [53:0] select_ln75_reg_1408;
wire   [0:0] icmp_ln75_fu_1157_p2;
reg   [0:0] icmp_ln75_reg_1413;
reg   [0:0] icmp_ln75_reg_1413_pp0_iter5_reg;
wire   [0:0] icmp_ln75_5_fu_1172_p2;
reg   [0:0] icmp_ln75_5_reg_1420;
reg   [0:0] icmp_ln75_5_reg_1420_pp0_iter5_reg;
wire   [10:0] select_ln75_5_fu_1190_p3;
reg   [10:0] select_ln75_5_reg_1425;
wire   [0:0] icmp_ln75_6_fu_1198_p2;
reg   [0:0] icmp_ln75_6_reg_1432;
reg   [0:0] icmp_ln75_6_reg_1432_pp0_iter5_reg;
wire   [15:0] trunc_ln75_8_fu_1204_p1;
reg   [15:0] trunc_ln75_8_reg_1438;
reg   [15:0] trunc_ln75_8_reg_1438_pp0_iter5_reg;
wire   [0:0] icmp_ln75_8_fu_1218_p2;
reg   [0:0] icmp_ln75_8_reg_1444;
wire   [15:0] select_ln75_7_fu_1248_p3;
reg   [15:0] select_ln75_7_reg_1449;
wire   [15:0] select_ln75_8_fu_1264_p3;
reg   [15:0] select_ln75_8_reg_1454;
reg    ap_condition_exit_pp0_iter8_stage0;
wire   [63:0] zext_ln75_fu_826_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] sum_fu_356;
wire   [31:0] grp_fu_1345_p3;
wire  signed [31:0] sext_ln71_8_cast_fu_783_p1;
reg   [31:0] ap_sig_allocacmp_sum_14;
wire    ap_loop_init;
reg   [6:0] j_fu_360;
wire   [6:0] add_ln73_fu_806_p2;
reg   [6:0] ap_sig_allocacmp_j_6;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
wire    ap_block_pp0_stage0_01001;
reg    dense_2_weights_ce0_local;
wire   [5:0] trunc_ln73_2_fu_812_p1;
wire   [10:0] add_ln75_8_fu_816_p4;
wire   [15:0] tmp_16_fu_831_p129;
wire   [63:0] bitcast_ln716_fu_1100_p1;
wire   [52:0] zext_ln75_15_cast_fu_1133_p3;
wire   [53:0] zext_ln75_6_fu_1140_p1;
wire   [53:0] sub_ln75_fu_1144_p2;
wire   [11:0] zext_ln75_5_fu_1130_p1;
wire   [11:0] sub_ln75_3_fu_1162_p2;
wire   [10:0] trunc_ln75_7_fu_1168_p1;
wire   [10:0] add_ln75_fu_1178_p2;
wire   [10:0] sub_ln75_4_fu_1184_p2;
wire   [6:0] tmp_15_fu_1208_p4;
wire   [53:0] zext_ln75_8_fu_1229_p1;
wire   [53:0] ashr_ln75_fu_1232_p2;
wire   [0:0] icmp_ln75_7_fu_1224_p2;
wire   [15:0] trunc_ln75_9_fu_1237_p1;
wire   [15:0] select_ln75_6_fu_1241_p3;
wire   [15:0] select_ln75_5cast_fu_1256_p1;
wire   [15:0] shl_ln75_fu_1259_p2;
wire   [0:0] xor_ln75_fu_1271_p2;
wire   [0:0] or_ln75_fu_1281_p2;
wire   [0:0] xor_ln75_2_fu_1285_p2;
wire   [0:0] and_ln75_fu_1276_p2;
wire   [0:0] and_ln75_2_fu_1291_p2;
wire   [15:0] ref_tmp_i_i274_s_fu_1305_p9;
wire   [2:0] ref_tmp_i_i274_s_fu_1305_p10;
wire  signed [15:0] ref_tmp_i_i274_s_fu_1305_p11;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [5:0] tmp_16_fu_831_p1;
wire   [5:0] tmp_16_fu_831_p3;
wire   [5:0] tmp_16_fu_831_p5;
wire   [5:0] tmp_16_fu_831_p7;
wire   [5:0] tmp_16_fu_831_p9;
wire   [5:0] tmp_16_fu_831_p11;
wire   [5:0] tmp_16_fu_831_p13;
wire   [5:0] tmp_16_fu_831_p15;
wire   [5:0] tmp_16_fu_831_p17;
wire   [5:0] tmp_16_fu_831_p19;
wire   [5:0] tmp_16_fu_831_p21;
wire   [5:0] tmp_16_fu_831_p23;
wire   [5:0] tmp_16_fu_831_p25;
wire   [5:0] tmp_16_fu_831_p27;
wire   [5:0] tmp_16_fu_831_p29;
wire   [5:0] tmp_16_fu_831_p31;
wire   [5:0] tmp_16_fu_831_p33;
wire   [5:0] tmp_16_fu_831_p35;
wire   [5:0] tmp_16_fu_831_p37;
wire   [5:0] tmp_16_fu_831_p39;
wire   [5:0] tmp_16_fu_831_p41;
wire   [5:0] tmp_16_fu_831_p43;
wire   [5:0] tmp_16_fu_831_p45;
wire   [5:0] tmp_16_fu_831_p47;
wire   [5:0] tmp_16_fu_831_p49;
wire   [5:0] tmp_16_fu_831_p51;
wire   [5:0] tmp_16_fu_831_p53;
wire   [5:0] tmp_16_fu_831_p55;
wire   [5:0] tmp_16_fu_831_p57;
wire   [5:0] tmp_16_fu_831_p59;
wire   [5:0] tmp_16_fu_831_p61;
wire   [5:0] tmp_16_fu_831_p63;
wire  signed [5:0] tmp_16_fu_831_p65;
wire  signed [5:0] tmp_16_fu_831_p67;
wire  signed [5:0] tmp_16_fu_831_p69;
wire  signed [5:0] tmp_16_fu_831_p71;
wire  signed [5:0] tmp_16_fu_831_p73;
wire  signed [5:0] tmp_16_fu_831_p75;
wire  signed [5:0] tmp_16_fu_831_p77;
wire  signed [5:0] tmp_16_fu_831_p79;
wire  signed [5:0] tmp_16_fu_831_p81;
wire  signed [5:0] tmp_16_fu_831_p83;
wire  signed [5:0] tmp_16_fu_831_p85;
wire  signed [5:0] tmp_16_fu_831_p87;
wire  signed [5:0] tmp_16_fu_831_p89;
wire  signed [5:0] tmp_16_fu_831_p91;
wire  signed [5:0] tmp_16_fu_831_p93;
wire  signed [5:0] tmp_16_fu_831_p95;
wire  signed [5:0] tmp_16_fu_831_p97;
wire  signed [5:0] tmp_16_fu_831_p99;
wire  signed [5:0] tmp_16_fu_831_p101;
wire  signed [5:0] tmp_16_fu_831_p103;
wire  signed [5:0] tmp_16_fu_831_p105;
wire  signed [5:0] tmp_16_fu_831_p107;
wire  signed [5:0] tmp_16_fu_831_p109;
wire  signed [5:0] tmp_16_fu_831_p111;
wire  signed [5:0] tmp_16_fu_831_p113;
wire  signed [5:0] tmp_16_fu_831_p115;
wire  signed [5:0] tmp_16_fu_831_p117;
wire  signed [5:0] tmp_16_fu_831_p119;
wire  signed [5:0] tmp_16_fu_831_p121;
wire  signed [5:0] tmp_16_fu_831_p123;
wire  signed [5:0] tmp_16_fu_831_p125;
wire  signed [5:0] tmp_16_fu_831_p127;
wire  signed [2:0] ref_tmp_i_i274_s_fu_1305_p1;
wire   [2:0] ref_tmp_i_i274_s_fu_1305_p3;
wire   [2:0] ref_tmp_i_i274_s_fu_1305_p5;
wire   [2:0] ref_tmp_i_i274_s_fu_1305_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 sum_fu_356 = 32'd0;
#0 j_fu_360 = 7'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) ecg_classify_trained_sparsemux_129_6_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 6'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 6'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 6'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 6'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 6'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 6'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 6'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 6'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 6'h8 ),
    .din8_WIDTH( 16 ),
    .CASE9( 6'h9 ),
    .din9_WIDTH( 16 ),
    .CASE10( 6'hA ),
    .din10_WIDTH( 16 ),
    .CASE11( 6'hB ),
    .din11_WIDTH( 16 ),
    .CASE12( 6'hC ),
    .din12_WIDTH( 16 ),
    .CASE13( 6'hD ),
    .din13_WIDTH( 16 ),
    .CASE14( 6'hE ),
    .din14_WIDTH( 16 ),
    .CASE15( 6'hF ),
    .din15_WIDTH( 16 ),
    .CASE16( 6'h10 ),
    .din16_WIDTH( 16 ),
    .CASE17( 6'h11 ),
    .din17_WIDTH( 16 ),
    .CASE18( 6'h12 ),
    .din18_WIDTH( 16 ),
    .CASE19( 6'h13 ),
    .din19_WIDTH( 16 ),
    .CASE20( 6'h14 ),
    .din20_WIDTH( 16 ),
    .CASE21( 6'h15 ),
    .din21_WIDTH( 16 ),
    .CASE22( 6'h16 ),
    .din22_WIDTH( 16 ),
    .CASE23( 6'h17 ),
    .din23_WIDTH( 16 ),
    .CASE24( 6'h18 ),
    .din24_WIDTH( 16 ),
    .CASE25( 6'h19 ),
    .din25_WIDTH( 16 ),
    .CASE26( 6'h1A ),
    .din26_WIDTH( 16 ),
    .CASE27( 6'h1B ),
    .din27_WIDTH( 16 ),
    .CASE28( 6'h1C ),
    .din28_WIDTH( 16 ),
    .CASE29( 6'h1D ),
    .din29_WIDTH( 16 ),
    .CASE30( 6'h1E ),
    .din30_WIDTH( 16 ),
    .CASE31( 6'h1F ),
    .din31_WIDTH( 16 ),
    .CASE32( 6'h20 ),
    .din32_WIDTH( 16 ),
    .CASE33( 6'h21 ),
    .din33_WIDTH( 16 ),
    .CASE34( 6'h22 ),
    .din34_WIDTH( 16 ),
    .CASE35( 6'h23 ),
    .din35_WIDTH( 16 ),
    .CASE36( 6'h24 ),
    .din36_WIDTH( 16 ),
    .CASE37( 6'h25 ),
    .din37_WIDTH( 16 ),
    .CASE38( 6'h26 ),
    .din38_WIDTH( 16 ),
    .CASE39( 6'h27 ),
    .din39_WIDTH( 16 ),
    .CASE40( 6'h28 ),
    .din40_WIDTH( 16 ),
    .CASE41( 6'h29 ),
    .din41_WIDTH( 16 ),
    .CASE42( 6'h2A ),
    .din42_WIDTH( 16 ),
    .CASE43( 6'h2B ),
    .din43_WIDTH( 16 ),
    .CASE44( 6'h2C ),
    .din44_WIDTH( 16 ),
    .CASE45( 6'h2D ),
    .din45_WIDTH( 16 ),
    .CASE46( 6'h2E ),
    .din46_WIDTH( 16 ),
    .CASE47( 6'h2F ),
    .din47_WIDTH( 16 ),
    .CASE48( 6'h30 ),
    .din48_WIDTH( 16 ),
    .CASE49( 6'h31 ),
    .din49_WIDTH( 16 ),
    .CASE50( 6'h32 ),
    .din50_WIDTH( 16 ),
    .CASE51( 6'h33 ),
    .din51_WIDTH( 16 ),
    .CASE52( 6'h34 ),
    .din52_WIDTH( 16 ),
    .CASE53( 6'h35 ),
    .din53_WIDTH( 16 ),
    .CASE54( 6'h36 ),
    .din54_WIDTH( 16 ),
    .CASE55( 6'h37 ),
    .din55_WIDTH( 16 ),
    .CASE56( 6'h38 ),
    .din56_WIDTH( 16 ),
    .CASE57( 6'h39 ),
    .din57_WIDTH( 16 ),
    .CASE58( 6'h3A ),
    .din58_WIDTH( 16 ),
    .CASE59( 6'h3B ),
    .din59_WIDTH( 16 ),
    .CASE60( 6'h3C ),
    .din60_WIDTH( 16 ),
    .CASE61( 6'h3D ),
    .din61_WIDTH( 16 ),
    .CASE62( 6'h3E ),
    .din62_WIDTH( 16 ),
    .CASE63( 6'h3F ),
    .din63_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
sparsemux_129_6_16_1_1_U730(
    .din0(hidden2),
    .din1(hidden2_1),
    .din2(hidden2_2),
    .din3(hidden2_3),
    .din4(hidden2_4),
    .din5(hidden2_5),
    .din6(hidden2_6),
    .din7(hidden2_7),
    .din8(hidden2_8),
    .din9(hidden2_9),
    .din10(hidden2_10),
    .din11(hidden2_11),
    .din12(hidden2_12),
    .din13(hidden2_13),
    .din14(hidden2_14),
    .din15(hidden2_15),
    .din16(hidden2_16),
    .din17(hidden2_17),
    .din18(hidden2_18),
    .din19(hidden2_19),
    .din20(hidden2_20),
    .din21(hidden2_21),
    .din22(hidden2_22),
    .din23(hidden2_23),
    .din24(hidden2_24),
    .din25(hidden2_25),
    .din26(hidden2_26),
    .din27(hidden2_27),
    .din28(hidden2_28),
    .din29(hidden2_29),
    .din30(hidden2_30),
    .din31(hidden2_31),
    .din32(hidden2_32),
    .din33(hidden2_33),
    .din34(hidden2_34),
    .din35(hidden2_35),
    .din36(hidden2_36),
    .din37(hidden2_37),
    .din38(hidden2_38),
    .din39(hidden2_39),
    .din40(hidden2_40),
    .din41(hidden2_41),
    .din42(hidden2_42),
    .din43(hidden2_43),
    .din44(hidden2_44),
    .din45(hidden2_45),
    .din46(hidden2_46),
    .din47(hidden2_47),
    .din48(hidden2_48),
    .din49(hidden2_49),
    .din50(hidden2_50),
    .din51(hidden2_51),
    .din52(hidden2_52),
    .din53(hidden2_53),
    .din54(hidden2_54),
    .din55(hidden2_55),
    .din56(hidden2_56),
    .din57(hidden2_57),
    .din58(hidden2_58),
    .din59(hidden2_59),
    .din60(hidden2_60),
    .din61(hidden2_61),
    .din62(hidden2_62),
    .din63(hidden2_63),
    .def(tmp_16_fu_831_p129),
    .sel(trunc_ln73_2_fu_812_p1),
    .dout(tmp_16_fu_831_p131)
);

(* dissolve_hierarchy = "yes" *) ecg_classify_trained_sparsemux_9_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_9_3_16_1_1_U731(
    .din0(16'd0),
    .din1(trunc_ln75_8_reg_1438_pp0_iter5_reg),
    .din2(select_ln75_7_reg_1449),
    .din3(select_ln75_8_reg_1454),
    .def(ref_tmp_i_i274_s_fu_1305_p9),
    .sel(ref_tmp_i_i274_s_fu_1305_p10),
    .dout(ref_tmp_i_i274_s_fu_1305_p11)
);

ecg_classify_trained_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U732(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_16_reg_1377_pp0_iter5_reg),
    .din1(ref_tmp_i_i274_s_fu_1305_p11),
    .din2(ap_sig_allocacmp_sum_14),
    .ce(1'b1),
    .dout(grp_fu_1345_p3)
);

ecg_classify_trained_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter8_stage0)) begin
            ap_enable_reg_pp0_iter9 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln73_fu_800_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_360 <= add_ln73_fu_806_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_360 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_fu_356 <= sext_ln71_8_cast_fu_783_p1;
        end else if ((ap_enable_reg_pp0_iter9 == 1'b1)) begin
            sum_fu_356 <= grp_fu_1345_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        dense_2_weights_load_reg_1382 <= dense_2_weights_q0;
        icmp_ln73_reg_1368 <= icmp_ln73_fu_800_p2;
        icmp_ln73_reg_1368_pp0_iter1_reg <= icmp_ln73_reg_1368;
        tmp_16_reg_1377 <= tmp_16_fu_831_p131;
        tmp_16_reg_1377_pp0_iter1_reg <= tmp_16_reg_1377;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        icmp_ln73_reg_1368_pp0_iter2_reg <= icmp_ln73_reg_1368_pp0_iter1_reg;
        icmp_ln73_reg_1368_pp0_iter3_reg <= icmp_ln73_reg_1368_pp0_iter2_reg;
        icmp_ln73_reg_1368_pp0_iter4_reg <= icmp_ln73_reg_1368_pp0_iter3_reg;
        icmp_ln73_reg_1368_pp0_iter5_reg <= icmp_ln73_reg_1368_pp0_iter4_reg;
        icmp_ln73_reg_1368_pp0_iter6_reg <= icmp_ln73_reg_1368_pp0_iter5_reg;
        icmp_ln73_reg_1368_pp0_iter7_reg <= icmp_ln73_reg_1368_pp0_iter6_reg;
        icmp_ln75_5_reg_1420 <= icmp_ln75_5_fu_1172_p2;
        icmp_ln75_5_reg_1420_pp0_iter5_reg <= icmp_ln75_5_reg_1420;
        icmp_ln75_6_reg_1432 <= icmp_ln75_6_fu_1198_p2;
        icmp_ln75_6_reg_1432_pp0_iter5_reg <= icmp_ln75_6_reg_1432;
        icmp_ln75_8_reg_1444 <= icmp_ln75_8_fu_1218_p2;
        icmp_ln75_reg_1413 <= icmp_ln75_fu_1157_p2;
        icmp_ln75_reg_1413_pp0_iter5_reg <= icmp_ln75_reg_1413;
        select_ln75_5_reg_1425 <= select_ln75_5_fu_1190_p3;
        select_ln75_7_reg_1449 <= select_ln75_7_fu_1248_p3;
        select_ln75_8_reg_1454 <= select_ln75_8_fu_1264_p3;
        select_ln75_reg_1408 <= select_ln75_fu_1150_p3;
        tmp_16_reg_1377_pp0_iter2_reg <= tmp_16_reg_1377_pp0_iter1_reg;
        tmp_16_reg_1377_pp0_iter3_reg <= tmp_16_reg_1377_pp0_iter2_reg;
        tmp_16_reg_1377_pp0_iter4_reg <= tmp_16_reg_1377_pp0_iter3_reg;
        tmp_16_reg_1377_pp0_iter5_reg <= tmp_16_reg_1377_pp0_iter4_reg;
        tmp_reg_1392 <= bitcast_ln716_fu_1100_p1[32'd63];
        tmp_reg_1392_pp0_iter4_reg <= tmp_reg_1392;
        tmp_s_reg_1398 <= {{bitcast_ln716_fu_1100_p1[62:52]}};
        trunc_ln75_6_reg_1403 <= trunc_ln75_6_fu_1126_p1;
        trunc_ln75_8_reg_1438 <= trunc_ln75_8_fu_1204_p1;
        trunc_ln75_8_reg_1438_pp0_iter5_reg <= trunc_ln75_8_reg_1438;
        trunc_ln75_reg_1387 <= trunc_ln75_fu_1104_p1;
    end
end

always @ (*) begin
    if (((icmp_ln73_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter8 == 1'b1) & (icmp_ln73_reg_1368_pp0_iter7_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter8_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter8_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_6 = 7'd0;
    end else begin
        ap_sig_allocacmp_j_6 = j_fu_360;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        ap_sig_allocacmp_sum_14 = grp_fu_1345_p3;
    end else begin
        ap_sig_allocacmp_sum_14 = sum_fu_356;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dense_2_weights_ce0_local = 1'b1;
    end else begin
        dense_2_weights_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (icmp_ln73_reg_1368_pp0_iter7_reg == 1'd1))) begin
        sum_34_out_ap_vld = 1'b1;
    end else begin
        sum_34_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln73_fu_806_p2 = (ap_sig_allocacmp_j_6 + 7'd1);

assign add_ln75_8_fu_816_p4 = {{{trunc_ln73_2_fu_812_p1}, {tmp_114}}, {2'd2}};

assign add_ln75_fu_1178_p2 = ($signed(trunc_ln75_7_fu_1168_p1) + $signed(11'd2040));

assign and_ln75_2_fu_1291_p2 = (xor_ln75_2_fu_1285_p2 & icmp_ln75_5_reg_1420_pp0_iter5_reg);

assign and_ln75_fu_1276_p2 = (xor_ln75_fu_1271_p2 & icmp_ln75_6_reg_1432_pp0_iter5_reg);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign ashr_ln75_fu_1232_p2 = $signed(select_ln75_reg_1408) >>> zext_ln75_8_fu_1229_p1;

assign bitcast_ln716_fu_1100_p1 = grp_fu_13213_p_dout0;

assign dense_2_weights_address0 = zext_ln75_fu_826_p1;

assign dense_2_weights_ce0 = dense_2_weights_ce0_local;

assign grp_fu_13213_p_ce = 1'b1;

assign grp_fu_13213_p_din0 = dense_2_weights_load_reg_1382;

assign icmp_ln73_fu_800_p2 = ((ap_sig_allocacmp_j_6 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln75_5_fu_1172_p2 = (($signed(sub_ln75_3_fu_1162_p2) > $signed(12'd8)) ? 1'b1 : 1'b0);

assign icmp_ln75_6_fu_1198_p2 = ((sub_ln75_3_fu_1162_p2 == 12'd8) ? 1'b1 : 1'b0);

assign icmp_ln75_7_fu_1224_p2 = ((select_ln75_5_reg_1425 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln75_8_fu_1218_p2 = ((tmp_15_fu_1208_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln75_fu_1157_p2 = ((trunc_ln75_reg_1387 == 63'd0) ? 1'b1 : 1'b0);

assign or_ln75_fu_1281_p2 = (icmp_ln75_reg_1413_pp0_iter5_reg | icmp_ln75_6_reg_1432_pp0_iter5_reg);

assign ref_tmp_i_i274_s_fu_1305_p10 = {{{icmp_ln75_reg_1413_pp0_iter5_reg}, {and_ln75_fu_1276_p2}}, {and_ln75_2_fu_1291_p2}};

assign ref_tmp_i_i274_s_fu_1305_p9 = 'bx;

assign select_ln75_5_fu_1190_p3 = ((icmp_ln75_5_fu_1172_p2[0:0] == 1'b1) ? add_ln75_fu_1178_p2 : sub_ln75_4_fu_1184_p2);

assign select_ln75_5cast_fu_1256_p1 = select_ln75_5_reg_1425;

assign select_ln75_6_fu_1241_p3 = ((tmp_reg_1392_pp0_iter4_reg[0:0] == 1'b1) ? 16'd65535 : 16'd0);

assign select_ln75_7_fu_1248_p3 = ((icmp_ln75_7_fu_1224_p2[0:0] == 1'b1) ? trunc_ln75_9_fu_1237_p1 : select_ln75_6_fu_1241_p3);

assign select_ln75_8_fu_1264_p3 = ((icmp_ln75_8_reg_1444[0:0] == 1'b1) ? shl_ln75_fu_1259_p2 : 16'd0);

assign select_ln75_fu_1150_p3 = ((tmp_reg_1392[0:0] == 1'b1) ? sub_ln75_fu_1144_p2 : zext_ln75_6_fu_1140_p1);

assign sext_ln71_8_cast_fu_783_p1 = $signed(sext_ln71_8);

assign shl_ln75_fu_1259_p2 = trunc_ln75_8_reg_1438 << select_ln75_5cast_fu_1256_p1;

assign sub_ln75_3_fu_1162_p2 = (12'd1075 - zext_ln75_5_fu_1130_p1);

assign sub_ln75_4_fu_1184_p2 = (11'd8 - trunc_ln75_7_fu_1168_p1);

assign sub_ln75_fu_1144_p2 = (54'd0 - zext_ln75_6_fu_1140_p1);

assign sum_34_out = ap_sig_allocacmp_sum_14[23:0];

assign tmp_15_fu_1208_p4 = {{select_ln75_5_fu_1190_p3[10:4]}};

assign tmp_16_fu_831_p129 = 'bx;

assign trunc_ln73_2_fu_812_p1 = ap_sig_allocacmp_j_6[5:0];

assign trunc_ln75_6_fu_1126_p1 = bitcast_ln716_fu_1100_p1[51:0];

assign trunc_ln75_7_fu_1168_p1 = sub_ln75_3_fu_1162_p2[10:0];

assign trunc_ln75_8_fu_1204_p1 = select_ln75_fu_1150_p3[15:0];

assign trunc_ln75_9_fu_1237_p1 = ashr_ln75_fu_1232_p2[15:0];

assign trunc_ln75_fu_1104_p1 = bitcast_ln716_fu_1100_p1[62:0];

assign xor_ln75_2_fu_1285_p2 = (or_ln75_fu_1281_p2 ^ 1'd1);

assign xor_ln75_fu_1271_p2 = (icmp_ln75_reg_1413_pp0_iter5_reg ^ 1'd1);

assign zext_ln75_15_cast_fu_1133_p3 = {{1'd1}, {trunc_ln75_6_reg_1403}};

assign zext_ln75_5_fu_1130_p1 = tmp_s_reg_1398;

assign zext_ln75_6_fu_1140_p1 = zext_ln75_15_cast_fu_1133_p3;

assign zext_ln75_8_fu_1229_p1 = select_ln75_5_reg_1425;

assign zext_ln75_fu_826_p1 = add_ln75_8_fu_816_p4;

endmodule //ecg_classify_trained_ecg_classify_trained_Pipeline_VITIS_LOOP_73_68
