-- ==============================================================
-- Generated by Vitis HLS v2024.1.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_classify_trained_ecg_classify_trained_Pipeline_VITIS_LOOP_88_810 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    hidden3 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_2 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_3 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_4 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_5 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_6 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_7 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_8 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_9 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_10 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_11 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_12 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_13 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_14 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_15 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_16 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_17 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_18 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_19 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_20 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_21 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_22 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_23 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_24 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_25 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_26 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_27 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_28 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_29 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_30 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden3_31 : IN STD_LOGIC_VECTOR (15 downto 0);
    sum_9_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    sum_9_out_ap_vld : OUT STD_LOGIC;
    dense_3_weights_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    dense_3_weights_ce0 : OUT STD_LOGIC;
    dense_3_weights_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_13213_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_13213_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_13213_p_ce : OUT STD_LOGIC );
end;


architecture behav of ecg_classify_trained_ecg_classify_trained_Pipeline_VITIS_LOOP_88_810 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_FFFFC200 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111100001000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_433 : STD_LOGIC_VECTOR (11 downto 0) := "010000110011";
    constant ap_const_lv12_8 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_const_lv11_7F8 : STD_LOGIC_VECTOR (10 downto 0) := "11111111000";
    constant ap_const_lv11_8 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv11_36 : STD_LOGIC_VECTOR (10 downto 0) := "00000110110";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln88_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln88_reg_944 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_944_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_944_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_944_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_944_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_944_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_944_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_944_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_533_p67 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_12_reg_953 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_12_reg_953_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_12_reg_953_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_12_reg_953_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_12_reg_953_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_12_reg_953_pp0_iter5_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal dense_3_weights_load_reg_958 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln90_fu_678_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln90_reg_963 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_9_reg_968 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_968_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_974 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln90_21_fu_700_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln90_21_reg_979 : STD_LOGIC_VECTOR (51 downto 0);
    signal select_ln90_2_fu_724_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln90_2_reg_984 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln90_3_fu_731_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_3_reg_989 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_3_reg_989_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln90_3_fu_764_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln90_3_reg_995 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln90_5_fu_772_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_5_reg_1002 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_5_reg_1002_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln90_23_fu_778_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln90_23_reg_1007 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln90_23_reg_1007_pp0_iter5_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln90_fu_792_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_reg_1013 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln90_3_fu_810_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln90_3_reg_1018 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln90_3_reg_1018_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln90_8_fu_840_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln90_8_reg_1023 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln90_9_fu_856_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln90_9_reg_1028 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_condition_exit_pp0_iter8_stage0 : STD_LOGIC;
    signal zext_ln90_12_fu_528_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sum_fu_232 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_921_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_sum_9 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal j_3_fu_236 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln88_fu_474_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_j : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal dense_3_weights_ce0_local : STD_LOGIC;
    signal trunc_ln88_5_fu_480_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_492_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl_fu_484_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln90_fu_500_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln90_fu_504_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_510_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln3_fu_520_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_12_fu_533_p65 : STD_LOGIC_VECTOR (15 downto 0);
    signal bitcast_ln716_fu_674_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln90_15_cast_fu_707_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln90_19_fu_714_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal sub_ln90_3_fu_718_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln90_2_fu_704_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln90_4_fu_736_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln90_22_fu_742_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln90_4_fu_746_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln90_2_fu_752_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln90_5_fu_758_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_11_fu_782_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln90_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln90_3_fu_804_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln90_7_fu_821_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln90_fu_824_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln90_11_fu_816_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln90_24_fu_829_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln90_fu_833_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln90_3cast_fu_848_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln90_fu_851_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xor_ln90_2_fu_863_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln90_2_fu_868_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ref_tmp_i_i30_9_fu_881_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal ref_tmp_i_i30_9_fu_881_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal ref_tmp_i_i30_9_fu_881_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_12_fu_533_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p5 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p7 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p9 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p11 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p13 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p15 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p17 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p19 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p21 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p23 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p25 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p27 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p29 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p31 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p33 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p35 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p37 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p39 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p41 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p43 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p45 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p47 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p49 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p51 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p53 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p55 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p57 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p59 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p61 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_533_p63 : STD_LOGIC_VECTOR (4 downto 0);
    signal ref_tmp_i_i30_9_fu_881_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal ref_tmp_i_i30_9_fu_881_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ref_tmp_i_i30_9_fu_881_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal ref_tmp_i_i30_9_fu_881_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component ecg_classify_trained_fpext_32ns_64_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component ecg_classify_trained_sparsemux_65_5_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (4 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (4 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (4 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (4 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (4 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (4 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (4 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (4 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (4 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (4 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (4 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (4 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (4 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (4 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (4 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (4 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (4 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (4 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (4 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (4 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (4 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (4 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (4 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (4 downto 0);
        din23_WIDTH : INTEGER;
        CASE24 : STD_LOGIC_VECTOR (4 downto 0);
        din24_WIDTH : INTEGER;
        CASE25 : STD_LOGIC_VECTOR (4 downto 0);
        din25_WIDTH : INTEGER;
        CASE26 : STD_LOGIC_VECTOR (4 downto 0);
        din26_WIDTH : INTEGER;
        CASE27 : STD_LOGIC_VECTOR (4 downto 0);
        din27_WIDTH : INTEGER;
        CASE28 : STD_LOGIC_VECTOR (4 downto 0);
        din28_WIDTH : INTEGER;
        CASE29 : STD_LOGIC_VECTOR (4 downto 0);
        din29_WIDTH : INTEGER;
        CASE30 : STD_LOGIC_VECTOR (4 downto 0);
        din30_WIDTH : INTEGER;
        CASE31 : STD_LOGIC_VECTOR (4 downto 0);
        din31_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (15 downto 0);
        din5 : IN STD_LOGIC_VECTOR (15 downto 0);
        din6 : IN STD_LOGIC_VECTOR (15 downto 0);
        din7 : IN STD_LOGIC_VECTOR (15 downto 0);
        din8 : IN STD_LOGIC_VECTOR (15 downto 0);
        din9 : IN STD_LOGIC_VECTOR (15 downto 0);
        din10 : IN STD_LOGIC_VECTOR (15 downto 0);
        din11 : IN STD_LOGIC_VECTOR (15 downto 0);
        din12 : IN STD_LOGIC_VECTOR (15 downto 0);
        din13 : IN STD_LOGIC_VECTOR (15 downto 0);
        din14 : IN STD_LOGIC_VECTOR (15 downto 0);
        din15 : IN STD_LOGIC_VECTOR (15 downto 0);
        din16 : IN STD_LOGIC_VECTOR (15 downto 0);
        din17 : IN STD_LOGIC_VECTOR (15 downto 0);
        din18 : IN STD_LOGIC_VECTOR (15 downto 0);
        din19 : IN STD_LOGIC_VECTOR (15 downto 0);
        din20 : IN STD_LOGIC_VECTOR (15 downto 0);
        din21 : IN STD_LOGIC_VECTOR (15 downto 0);
        din22 : IN STD_LOGIC_VECTOR (15 downto 0);
        din23 : IN STD_LOGIC_VECTOR (15 downto 0);
        din24 : IN STD_LOGIC_VECTOR (15 downto 0);
        din25 : IN STD_LOGIC_VECTOR (15 downto 0);
        din26 : IN STD_LOGIC_VECTOR (15 downto 0);
        din27 : IN STD_LOGIC_VECTOR (15 downto 0);
        din28 : IN STD_LOGIC_VECTOR (15 downto 0);
        din29 : IN STD_LOGIC_VECTOR (15 downto 0);
        din30 : IN STD_LOGIC_VECTOR (15 downto 0);
        din31 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component ecg_classify_trained_sparsemux_9_3_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component ecg_classify_trained_mac_muladd_16s_16s_32ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_classify_trained_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_65_5_16_1_1_U913 : component ecg_classify_trained_sparsemux_65_5_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00000",
        din0_WIDTH => 16,
        CASE1 => "00001",
        din1_WIDTH => 16,
        CASE2 => "00010",
        din2_WIDTH => 16,
        CASE3 => "00011",
        din3_WIDTH => 16,
        CASE4 => "00100",
        din4_WIDTH => 16,
        CASE5 => "00101",
        din5_WIDTH => 16,
        CASE6 => "00110",
        din6_WIDTH => 16,
        CASE7 => "00111",
        din7_WIDTH => 16,
        CASE8 => "01000",
        din8_WIDTH => 16,
        CASE9 => "01001",
        din9_WIDTH => 16,
        CASE10 => "01010",
        din10_WIDTH => 16,
        CASE11 => "01011",
        din11_WIDTH => 16,
        CASE12 => "01100",
        din12_WIDTH => 16,
        CASE13 => "01101",
        din13_WIDTH => 16,
        CASE14 => "01110",
        din14_WIDTH => 16,
        CASE15 => "01111",
        din15_WIDTH => 16,
        CASE16 => "10000",
        din16_WIDTH => 16,
        CASE17 => "10001",
        din17_WIDTH => 16,
        CASE18 => "10010",
        din18_WIDTH => 16,
        CASE19 => "10011",
        din19_WIDTH => 16,
        CASE20 => "10100",
        din20_WIDTH => 16,
        CASE21 => "10101",
        din21_WIDTH => 16,
        CASE22 => "10110",
        din22_WIDTH => 16,
        CASE23 => "10111",
        din23_WIDTH => 16,
        CASE24 => "11000",
        din24_WIDTH => 16,
        CASE25 => "11001",
        din25_WIDTH => 16,
        CASE26 => "11010",
        din26_WIDTH => 16,
        CASE27 => "11011",
        din27_WIDTH => 16,
        CASE28 => "11100",
        din28_WIDTH => 16,
        CASE29 => "11101",
        din29_WIDTH => 16,
        CASE30 => "11110",
        din30_WIDTH => 16,
        CASE31 => "11111",
        din31_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 5,
        dout_WIDTH => 16)
    port map (
        din0 => hidden3,
        din1 => hidden3_1,
        din2 => hidden3_2,
        din3 => hidden3_3,
        din4 => hidden3_4,
        din5 => hidden3_5,
        din6 => hidden3_6,
        din7 => hidden3_7,
        din8 => hidden3_8,
        din9 => hidden3_9,
        din10 => hidden3_10,
        din11 => hidden3_11,
        din12 => hidden3_12,
        din13 => hidden3_13,
        din14 => hidden3_14,
        din15 => hidden3_15,
        din16 => hidden3_16,
        din17 => hidden3_17,
        din18 => hidden3_18,
        din19 => hidden3_19,
        din20 => hidden3_20,
        din21 => hidden3_21,
        din22 => hidden3_22,
        din23 => hidden3_23,
        din24 => hidden3_24,
        din25 => hidden3_25,
        din26 => hidden3_26,
        din27 => hidden3_27,
        din28 => hidden3_28,
        din29 => hidden3_29,
        din30 => hidden3_30,
        din31 => hidden3_31,
        def => tmp_12_fu_533_p65,
        sel => trunc_ln88_5_fu_480_p1,
        dout => tmp_12_fu_533_p67);

    sparsemux_9_3_16_1_1_U914 : component ecg_classify_trained_sparsemux_9_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 16,
        CASE1 => "010",
        din1_WIDTH => 16,
        CASE2 => "001",
        din2_WIDTH => 16,
        CASE3 => "000",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_0,
        din1 => trunc_ln90_23_reg_1007_pp0_iter5_reg,
        din2 => select_ln90_8_reg_1023,
        din3 => select_ln90_9_reg_1028,
        def => ref_tmp_i_i30_9_fu_881_p9,
        sel => ref_tmp_i_i30_9_fu_881_p10,
        dout => ref_tmp_i_i30_9_fu_881_p11);

    mac_muladd_16s_16s_32ns_32_4_1_U915 : component ecg_classify_trained_mac_muladd_16s_16s_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_12_reg_953_pp0_iter5_reg,
        din1 => ref_tmp_i_i30_9_fu_881_p11,
        din2 => ap_sig_allocacmp_sum_9,
        ce => ap_const_logic_1,
        dout => grp_fu_921_p3);

    flow_control_loop_pipe_sequential_init_U : component ecg_classify_trained_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter8_stage0)) then 
                    ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    j_3_fu_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln88_fu_468_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_3_fu_236 <= add_ln88_fu_474_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_3_fu_236 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    sum_fu_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    sum_fu_232 <= ap_const_lv32_FFFFC200;
                elsif ((ap_enable_reg_pp0_iter9 = ap_const_logic_1)) then 
                    sum_fu_232 <= grp_fu_921_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln90_3_reg_1018 <= and_ln90_3_fu_810_p2;
                and_ln90_3_reg_1018_pp0_iter5_reg <= and_ln90_3_reg_1018;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                icmp_ln88_reg_944_pp0_iter2_reg <= icmp_ln88_reg_944_pp0_iter1_reg;
                icmp_ln88_reg_944_pp0_iter3_reg <= icmp_ln88_reg_944_pp0_iter2_reg;
                icmp_ln88_reg_944_pp0_iter4_reg <= icmp_ln88_reg_944_pp0_iter3_reg;
                icmp_ln88_reg_944_pp0_iter5_reg <= icmp_ln88_reg_944_pp0_iter4_reg;
                icmp_ln88_reg_944_pp0_iter6_reg <= icmp_ln88_reg_944_pp0_iter5_reg;
                icmp_ln88_reg_944_pp0_iter7_reg <= icmp_ln88_reg_944_pp0_iter6_reg;
                icmp_ln90_3_reg_989 <= icmp_ln90_3_fu_731_p2;
                icmp_ln90_3_reg_989_pp0_iter5_reg <= icmp_ln90_3_reg_989;
                icmp_ln90_5_reg_1002 <= icmp_ln90_5_fu_772_p2;
                icmp_ln90_5_reg_1002_pp0_iter5_reg <= icmp_ln90_5_reg_1002;
                icmp_ln90_reg_1013 <= icmp_ln90_fu_792_p2;
                select_ln90_2_reg_984 <= select_ln90_2_fu_724_p3;
                select_ln90_3_reg_995 <= select_ln90_3_fu_764_p3;
                select_ln90_8_reg_1023 <= select_ln90_8_fu_840_p3;
                select_ln90_9_reg_1028 <= select_ln90_9_fu_856_p3;
                tmp_10_reg_974 <= bitcast_ln716_fu_674_p1(62 downto 52);
                tmp_12_reg_953_pp0_iter2_reg <= tmp_12_reg_953_pp0_iter1_reg;
                tmp_12_reg_953_pp0_iter3_reg <= tmp_12_reg_953_pp0_iter2_reg;
                tmp_12_reg_953_pp0_iter4_reg <= tmp_12_reg_953_pp0_iter3_reg;
                tmp_12_reg_953_pp0_iter5_reg <= tmp_12_reg_953_pp0_iter4_reg;
                tmp_9_reg_968 <= bitcast_ln716_fu_674_p1(63 downto 63);
                tmp_9_reg_968_pp0_iter4_reg <= tmp_9_reg_968;
                trunc_ln90_21_reg_979 <= trunc_ln90_21_fu_700_p1;
                trunc_ln90_23_reg_1007 <= trunc_ln90_23_fu_778_p1;
                trunc_ln90_23_reg_1007_pp0_iter5_reg <= trunc_ln90_23_reg_1007;
                trunc_ln90_reg_963 <= trunc_ln90_fu_678_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                dense_3_weights_load_reg_958 <= dense_3_weights_q0;
                icmp_ln88_reg_944 <= icmp_ln88_fu_468_p2;
                icmp_ln88_reg_944_pp0_iter1_reg <= icmp_ln88_reg_944;
                tmp_12_reg_953 <= tmp_12_fu_533_p67;
                tmp_12_reg_953_pp0_iter1_reg <= tmp_12_reg_953;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln88_fu_474_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j) + unsigned(ap_const_lv6_1));
    add_ln90_2_fu_752_p2 <= std_logic_vector(unsigned(trunc_ln90_22_fu_742_p1) + unsigned(ap_const_lv11_7F8));
    and_ln90_2_fu_868_p2 <= (xor_ln90_2_fu_863_p2 and icmp_ln90_5_reg_1002_pp0_iter5_reg);
    and_ln90_3_fu_810_p2 <= (xor_ln90_3_fu_804_p2 and icmp_ln90_4_fu_746_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln88_fu_468_p2)
    begin
        if (((icmp_ln88_fu_468_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter8_stage0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_subdone, icmp_ln88_reg_944_pp0_iter7_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (icmp_ln88_reg_944_pp0_iter7_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter8_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter8_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter8_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, j_3_fu_236)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_j <= j_3_fu_236;
        end if; 
    end process;


    ap_sig_allocacmp_sum_9_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0, sum_fu_232, grp_fu_921_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            ap_sig_allocacmp_sum_9 <= grp_fu_921_p3;
        else 
            ap_sig_allocacmp_sum_9 <= sum_fu_232;
        end if; 
    end process;

    ashr_ln90_fu_824_p2 <= std_logic_vector(shift_right(signed(select_ln90_2_reg_984),to_integer(unsigned('0' & zext_ln90_7_fu_821_p1(31-1 downto 0)))));
    bitcast_ln716_fu_674_p1 <= grp_fu_13213_p_dout0;
    dense_3_weights_address0 <= zext_ln90_12_fu_528_p1(8 - 1 downto 0);
    dense_3_weights_ce0 <= dense_3_weights_ce0_local;

    dense_3_weights_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dense_3_weights_ce0_local <= ap_const_logic_1;
        else 
            dense_3_weights_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_13213_p_ce <= ap_const_logic_1;
    grp_fu_13213_p_din0 <= dense_3_weights_load_reg_958;
    icmp_ln88_fu_468_p2 <= "1" when (ap_sig_allocacmp_j = ap_const_lv6_20) else "0";
    icmp_ln90_11_fu_816_p2 <= "1" when (unsigned(select_ln90_3_reg_995) < unsigned(ap_const_lv11_36)) else "0";
    icmp_ln90_3_fu_731_p2 <= "1" when (trunc_ln90_reg_963 = ap_const_lv63_0) else "0";
    icmp_ln90_4_fu_746_p2 <= "1" when (signed(sub_ln90_4_fu_736_p2) > signed(ap_const_lv12_8)) else "0";
    icmp_ln90_5_fu_772_p2 <= "1" when (sub_ln90_4_fu_736_p2 = ap_const_lv12_8) else "0";
    icmp_ln90_fu_792_p2 <= "1" when (tmp_11_fu_782_p4 = ap_const_lv7_0) else "0";
    or_ln3_fu_520_p3 <= (tmp_s_fu_510_p4 & ap_const_lv1_1);
    or_ln90_fu_798_p2 <= (icmp_ln90_5_fu_772_p2 or icmp_ln90_3_fu_731_p2);
    p_shl_fu_484_p3 <= (trunc_ln88_5_fu_480_p1 & ap_const_lv3_0);
    ref_tmp_i_i30_9_fu_881_p10 <= ((icmp_ln90_3_reg_989_pp0_iter5_reg & and_ln90_2_fu_868_p2) & and_ln90_3_reg_1018_pp0_iter5_reg);
    ref_tmp_i_i30_9_fu_881_p9 <= "XXXXXXXXXXXXXXXX";
    select_ln90_2_fu_724_p3 <= 
        sub_ln90_3_fu_718_p2 when (tmp_9_reg_968(0) = '1') else 
        zext_ln90_19_fu_714_p1;
    select_ln90_3_fu_764_p3 <= 
        add_ln90_2_fu_752_p2 when (icmp_ln90_4_fu_746_p2(0) = '1') else 
        sub_ln90_5_fu_758_p2;
    select_ln90_3cast_fu_848_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln90_3_reg_995),16));
    select_ln90_8_fu_840_p3 <= 
        trunc_ln90_24_fu_829_p1 when (icmp_ln90_11_fu_816_p2(0) = '1') else 
        select_ln90_fu_833_p3;
    select_ln90_9_fu_856_p3 <= 
        shl_ln90_fu_851_p2 when (icmp_ln90_reg_1013(0) = '1') else 
        ap_const_lv16_0;
    select_ln90_fu_833_p3 <= 
        ap_const_lv16_FFFF when (tmp_9_reg_968_pp0_iter4_reg(0) = '1') else 
        ap_const_lv16_0;
    shl_ln90_fu_851_p2 <= std_logic_vector(shift_left(unsigned(trunc_ln90_23_reg_1007),to_integer(unsigned('0' & select_ln90_3cast_fu_848_p1(16-1 downto 0)))));
    sub_ln90_3_fu_718_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(zext_ln90_19_fu_714_p1));
    sub_ln90_4_fu_736_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(zext_ln90_2_fu_704_p1));
    sub_ln90_5_fu_758_p2 <= std_logic_vector(unsigned(ap_const_lv11_8) - unsigned(trunc_ln90_22_fu_742_p1));
    sub_ln90_fu_504_p2 <= std_logic_vector(unsigned(p_shl_fu_484_p3) - unsigned(zext_ln90_fu_500_p1));
    sum_9_out <= ap_sig_allocacmp_sum_9(24 - 1 downto 0);

    sum_9_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_944_pp0_iter7_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (icmp_ln88_reg_944_pp0_iter7_reg = ap_const_lv1_1))) then 
            sum_9_out_ap_vld <= ap_const_logic_1;
        else 
            sum_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_11_fu_782_p4 <= select_ln90_3_fu_764_p3(10 downto 4);
    tmp_12_fu_533_p65 <= "XXXXXXXXXXXXXXXX";
    tmp_fu_492_p3 <= (ap_sig_allocacmp_j & ap_const_lv1_0);
    tmp_s_fu_510_p4 <= sub_ln90_fu_504_p2(7 downto 1);
    trunc_ln88_5_fu_480_p1 <= ap_sig_allocacmp_j(5 - 1 downto 0);
    trunc_ln90_21_fu_700_p1 <= bitcast_ln716_fu_674_p1(52 - 1 downto 0);
    trunc_ln90_22_fu_742_p1 <= sub_ln90_4_fu_736_p2(11 - 1 downto 0);
    trunc_ln90_23_fu_778_p1 <= select_ln90_2_fu_724_p3(16 - 1 downto 0);
    trunc_ln90_24_fu_829_p1 <= ashr_ln90_fu_824_p2(16 - 1 downto 0);
    trunc_ln90_fu_678_p1 <= bitcast_ln716_fu_674_p1(63 - 1 downto 0);
    xor_ln90_2_fu_863_p2 <= (icmp_ln90_3_reg_989_pp0_iter5_reg xor ap_const_lv1_1);
    xor_ln90_3_fu_804_p2 <= (or_ln90_fu_798_p2 xor ap_const_lv1_1);
    zext_ln90_12_fu_528_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln3_fu_520_p3),64));
    zext_ln90_15_cast_fu_707_p3 <= (ap_const_lv1_1 & trunc_ln90_21_reg_979);
    zext_ln90_19_fu_714_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln90_15_cast_fu_707_p3),54));
    zext_ln90_2_fu_704_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_reg_974),12));
    zext_ln90_7_fu_821_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln90_3_reg_995),54));
    zext_ln90_fu_500_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_492_p3),8));
end behav;
