-- ==============================================================
-- Generated by Vitis HLS v2024.1.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_classify_trained_ecg_classify_trained_Pipeline_VITIS_LOOP_41_21 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln39_5 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_cast_cast : IN STD_LOGIC_VECTOR (61 downto 0);
    tmp_109 : IN STD_LOGIC_VECTOR (5 downto 0);
    sum_19_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    sum_19_out_ap_vld : OUT STD_LOGIC;
    dense_weights_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    dense_weights_ce0 : OUT STD_LOGIC;
    dense_weights_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_13213_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_13213_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_13213_p_ce : OUT STD_LOGIC );
end;


architecture behav of ecg_classify_trained_ecg_classify_trained_Pipeline_VITIS_LOOP_41_21 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_2E : STD_LOGIC_VECTOR (5 downto 0) := "101110";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_433 : STD_LOGIC_VECTOR (11 downto 0) := "010000110011";
    constant ap_const_lv12_8 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_const_lv11_7F8 : STD_LOGIC_VECTOR (10 downto 0) := "11111111000";
    constant ap_const_lv11_8 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv11_36 : STD_LOGIC_VECTOR (10 downto 0) := "00000110110";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln41_reg_565 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_reg_565_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln41_reg_569 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln41_reg_569_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op70_read_state6 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln41_fu_215_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln41_reg_565_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_reg_565_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_reg_565_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_reg_565_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_reg_565_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_reg_565_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln41_fu_227_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln41_reg_569_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln41_reg_569_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln41_reg_569_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln41_reg_569_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal dense_weights_load_reg_578 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln43_fu_255_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln43_reg_583 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_reg_588 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_588_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_594 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln43_13_fu_277_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln43_13_reg_599 : STD_LOGIC_VECTOR (51 downto 0);
    signal select_ln43_4_fu_301_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln43_4_reg_604 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln43_5_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_5_reg_609 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_5_reg_609_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_6_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_6_reg_616 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_6_reg_616_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln43_5_fu_341_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln43_5_reg_621 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln43_7_fu_349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_7_reg_628 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_7_reg_628_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln43_15_fu_355_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln43_15_reg_634 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln43_15_reg_634_pp0_iter5_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln43_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_640 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln43_6_fu_405_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln43_6_reg_645 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln43_7_fu_421_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln43_7_reg_650 : STD_LOGIC_VECTOR (15 downto 0);
    signal gmem0_addr_read_reg_655 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter8_stage0 : STD_LOGIC;
    signal ap_phi_mux_empty_40_phi_fu_180_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter6_empty_40_reg_177 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln41_fu_431_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln43_fu_241_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shiftreg869_fu_122 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal sum_19_fu_126 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_530_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln39_5_cast_fu_193_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_sum : STD_LOGIC_VECTOR (31 downto 0);
    signal j_7_fu_130 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln41_fu_221_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_j : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal dense_weights_ce0_local : STD_LOGIC;
    signal add_ln43_4_fu_231_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal bitcast_ln716_fu_251_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln43_12_cast_fu_284_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln43_9_fu_291_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal sub_ln43_3_fu_295_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln43_3_fu_281_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln43_4_fu_313_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln43_14_fu_319_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln43_fu_329_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln43_fu_335_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_24_fu_359_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln43_5_fu_386_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln43_fu_389_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln43_8_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln43_16_fu_394_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln43_fu_398_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln43_5cast_fu_413_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln43_fu_416_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xor_ln43_2_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln43_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln43_2_fu_441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln43_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ref_tmp_i_i32_9_fu_470_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal ref_tmp_i_i32_9_fu_470_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln43_18_fu_491_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ref_tmp_i_i32_9_fu_470_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_186_ce : STD_LOGIC;
    signal grp_fu_530_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ref_tmp_i_i32_9_fu_470_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal ref_tmp_i_i32_9_fu_470_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ref_tmp_i_i32_9_fu_470_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal ref_tmp_i_i32_9_fu_470_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component ecg_classify_trained_fpext_32ns_64_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component ecg_classify_trained_sparsemux_9_3_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component ecg_classify_trained_mac_muladd_16s_16s_32ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_classify_trained_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_3_16_1_1_U13 : component ecg_classify_trained_sparsemux_9_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 16,
        CASE1 => "010",
        din1_WIDTH => 16,
        CASE2 => "001",
        din2_WIDTH => 16,
        CASE3 => "000",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_0,
        din1 => trunc_ln43_15_reg_634_pp0_iter5_reg,
        din2 => select_ln43_6_reg_645,
        din3 => select_ln43_7_reg_650,
        def => ref_tmp_i_i32_9_fu_470_p9,
        sel => ref_tmp_i_i32_9_fu_470_p10,
        dout => ref_tmp_i_i32_9_fu_470_p11);

    mac_muladd_16s_16s_32ns_32_4_1_U14 : component ecg_classify_trained_mac_muladd_16s_16s_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => trunc_ln43_18_fu_491_p1,
        din1 => ref_tmp_i_i32_9_fu_470_p11,
        din2 => ap_sig_allocacmp_sum,
        ce => grp_fu_530_ce,
        dout => grp_fu_530_p3);

    flow_control_loop_pipe_sequential_init_U : component ecg_classify_trained_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter8_stage0)) then 
                    ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    j_7_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln41_fu_215_p2 = ap_const_lv1_0))) then 
                    j_7_fu_130 <= add_ln41_fu_221_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_7_fu_130 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    shiftreg869_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    shiftreg869_fu_122 <= ap_const_lv16_0;
                elsif (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln41_reg_565_pp0_iter5_reg = ap_const_lv1_0))) then 
                    shiftreg869_fu_122 <= ap_phi_mux_empty_40_phi_fu_180_p4(31 downto 16);
                end if;
            end if; 
        end if;
    end process;

    sum_19_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    sum_19_fu_126 <= sext_ln39_5_cast_fu_193_p1;
                elsif ((ap_enable_reg_pp0_iter9 = ap_const_logic_1)) then 
                    sum_19_fu_126 <= grp_fu_530_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                dense_weights_load_reg_578 <= dense_weights_q0;
                icmp_ln41_reg_565 <= icmp_ln41_fu_215_p2;
                icmp_ln41_reg_565_pp0_iter1_reg <= icmp_ln41_reg_565;
                trunc_ln41_reg_569 <= trunc_ln41_fu_227_p1;
                trunc_ln41_reg_569_pp0_iter1_reg <= trunc_ln41_reg_569;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                gmem0_addr_read_reg_655 <= m_axi_gmem0_RDATA;
                icmp_ln41_reg_565_pp0_iter2_reg <= icmp_ln41_reg_565_pp0_iter1_reg;
                icmp_ln41_reg_565_pp0_iter3_reg <= icmp_ln41_reg_565_pp0_iter2_reg;
                icmp_ln41_reg_565_pp0_iter4_reg <= icmp_ln41_reg_565_pp0_iter3_reg;
                icmp_ln41_reg_565_pp0_iter5_reg <= icmp_ln41_reg_565_pp0_iter4_reg;
                icmp_ln41_reg_565_pp0_iter6_reg <= icmp_ln41_reg_565_pp0_iter5_reg;
                icmp_ln41_reg_565_pp0_iter7_reg <= icmp_ln41_reg_565_pp0_iter6_reg;
                icmp_ln43_5_reg_609 <= icmp_ln43_5_fu_308_p2;
                icmp_ln43_5_reg_609_pp0_iter5_reg <= icmp_ln43_5_reg_609;
                icmp_ln43_6_reg_616 <= icmp_ln43_6_fu_323_p2;
                icmp_ln43_6_reg_616_pp0_iter5_reg <= icmp_ln43_6_reg_616;
                icmp_ln43_7_reg_628 <= icmp_ln43_7_fu_349_p2;
                icmp_ln43_7_reg_628_pp0_iter5_reg <= icmp_ln43_7_reg_628;
                icmp_ln43_reg_640 <= icmp_ln43_fu_369_p2;
                select_ln43_4_reg_604 <= select_ln43_4_fu_301_p3;
                select_ln43_5_reg_621 <= select_ln43_5_fu_341_p3;
                select_ln43_6_reg_645 <= select_ln43_6_fu_405_p3;
                select_ln43_7_reg_650 <= select_ln43_7_fu_421_p3;
                tmp_reg_588 <= bitcast_ln716_fu_251_p1(63 downto 63);
                tmp_reg_588_pp0_iter4_reg <= tmp_reg_588;
                tmp_s_reg_594 <= bitcast_ln716_fu_251_p1(62 downto 52);
                trunc_ln41_reg_569_pp0_iter2_reg <= trunc_ln41_reg_569_pp0_iter1_reg;
                trunc_ln41_reg_569_pp0_iter3_reg <= trunc_ln41_reg_569_pp0_iter2_reg;
                trunc_ln41_reg_569_pp0_iter4_reg <= trunc_ln41_reg_569_pp0_iter3_reg;
                trunc_ln41_reg_569_pp0_iter5_reg <= trunc_ln41_reg_569_pp0_iter4_reg;
                trunc_ln43_13_reg_599 <= trunc_ln43_13_fu_277_p1;
                trunc_ln43_15_reg_634 <= trunc_ln43_15_fu_355_p1;
                trunc_ln43_15_reg_634_pp0_iter5_reg <= trunc_ln43_15_reg_634;
                trunc_ln43_reg_583 <= trunc_ln43_fu_255_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln41_fu_221_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j) + unsigned(ap_const_lv6_1));
    add_ln43_4_fu_231_p4 <= ((ap_sig_allocacmp_j & tmp_109) & ap_const_lv1_1);
    add_ln43_fu_329_p2 <= std_logic_vector(unsigned(trunc_ln43_14_fu_319_p1) + unsigned(ap_const_lv11_7F8));
    and_ln43_2_fu_441_p2 <= (xor_ln43_2_fu_436_p2 and icmp_ln43_7_reg_628_pp0_iter5_reg);
    and_ln43_fu_456_p2 <= (xor_ln43_fu_450_p2 and icmp_ln43_6_reg_616_pp0_iter5_reg);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_state6_pp0_stage0_iter5)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_state6_pp0_stage0_iter5)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_state6_pp0_stage0_iter5)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5));
    end process;


    ap_block_state6_pp0_stage0_iter5_assign_proc : process(m_axi_gmem0_RVALID, ap_predicate_op70_read_state6)
    begin
                ap_block_state6_pp0_stage0_iter5 <= ((m_axi_gmem0_RVALID = ap_const_logic_0) and (ap_predicate_op70_read_state6 = ap_const_boolean_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln41_fu_215_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln41_fu_215_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter8_stage0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_subdone, icmp_ln41_reg_565_pp0_iter7_reg)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (icmp_ln41_reg_565_pp0_iter7_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter8_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter8_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter8_reg, ap_done_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_empty_40_phi_fu_180_p4_assign_proc : process(icmp_ln41_reg_565_pp0_iter5_reg, trunc_ln41_reg_569_pp0_iter5_reg, gmem0_addr_read_reg_655, ap_phi_reg_pp0_iter6_empty_40_reg_177, zext_ln41_fu_431_p1)
    begin
        if ((icmp_ln41_reg_565_pp0_iter5_reg = ap_const_lv1_0)) then
            if ((trunc_ln41_reg_569_pp0_iter5_reg = ap_const_lv1_1)) then 
                ap_phi_mux_empty_40_phi_fu_180_p4 <= zext_ln41_fu_431_p1;
            elsif ((trunc_ln41_reg_569_pp0_iter5_reg = ap_const_lv1_0)) then 
                ap_phi_mux_empty_40_phi_fu_180_p4 <= gmem0_addr_read_reg_655;
            else 
                ap_phi_mux_empty_40_phi_fu_180_p4 <= ap_phi_reg_pp0_iter6_empty_40_reg_177;
            end if;
        else 
            ap_phi_mux_empty_40_phi_fu_180_p4 <= ap_phi_reg_pp0_iter6_empty_40_reg_177;
        end if; 
    end process;

    ap_phi_reg_pp0_iter6_empty_40_reg_177 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op70_read_state6_assign_proc : process(icmp_ln41_reg_565_pp0_iter4_reg, trunc_ln41_reg_569_pp0_iter4_reg)
    begin
                ap_predicate_op70_read_state6 <= ((trunc_ln41_reg_569_pp0_iter4_reg = ap_const_lv1_0) and (icmp_ln41_reg_565_pp0_iter4_reg = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, j_7_fu_130)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_j <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_j <= j_7_fu_130;
        end if; 
    end process;


    ap_sig_allocacmp_sum_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0, sum_19_fu_126, grp_fu_530_p3)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_sum <= grp_fu_530_p3;
        else 
            ap_sig_allocacmp_sum <= sum_19_fu_126;
        end if; 
    end process;

    ashr_ln43_fu_389_p2 <= std_logic_vector(shift_right(signed(select_ln43_4_reg_604),to_integer(unsigned('0' & zext_ln43_5_fu_386_p1(31-1 downto 0)))));
    bitcast_ln716_fu_251_p1 <= grp_fu_13213_p_dout0;
    dense_weights_address0 <= zext_ln43_fu_241_p1(13 - 1 downto 0);
    dense_weights_ce0 <= dense_weights_ce0_local;

    dense_weights_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dense_weights_ce0_local <= ap_const_logic_1;
        else 
            dense_weights_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    gmem0_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter5, m_axi_gmem0_RVALID, ap_predicate_op70_read_state6, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op70_read_state6 = ap_const_boolean_1))) then 
            gmem0_blk_n_R <= m_axi_gmem0_RVALID;
        else 
            gmem0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_13213_p_ce <= grp_fu_186_ce;
    grp_fu_13213_p_din0 <= dense_weights_load_reg_578;

    grp_fu_186_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_186_ce <= ap_const_logic_1;
        else 
            grp_fu_186_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_530_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_530_ce <= ap_const_logic_1;
        else 
            grp_fu_530_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln41_fu_215_p2 <= "1" when (ap_sig_allocacmp_j = ap_const_lv6_2E) else "0";
    icmp_ln43_5_fu_308_p2 <= "1" when (trunc_ln43_reg_583 = ap_const_lv63_0) else "0";
    icmp_ln43_6_fu_323_p2 <= "1" when (signed(sub_ln43_4_fu_313_p2) > signed(ap_const_lv12_8)) else "0";
    icmp_ln43_7_fu_349_p2 <= "1" when (sub_ln43_4_fu_313_p2 = ap_const_lv12_8) else "0";
    icmp_ln43_8_fu_381_p2 <= "1" when (unsigned(select_ln43_5_reg_621) < unsigned(ap_const_lv11_36)) else "0";
    icmp_ln43_fu_369_p2 <= "1" when (tmp_24_fu_359_p4 = ap_const_lv7_0) else "0";
    m_axi_gmem0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_ARVALID <= ap_const_logic_0;
    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter5, ap_predicate_op70_read_state6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op70_read_state6 = ap_const_boolean_1))) then 
            m_axi_gmem0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_WDATA <= ap_const_lv32_0;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv4_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;
    or_ln43_fu_446_p2 <= (icmp_ln43_7_reg_628_pp0_iter5_reg or icmp_ln43_5_reg_609_pp0_iter5_reg);
    ref_tmp_i_i32_9_fu_470_p10 <= ((icmp_ln43_5_reg_609_pp0_iter5_reg & and_ln43_2_fu_441_p2) & and_ln43_fu_456_p2);
    ref_tmp_i_i32_9_fu_470_p9 <= "XXXXXXXXXXXXXXXX";
    select_ln43_4_fu_301_p3 <= 
        sub_ln43_3_fu_295_p2 when (tmp_reg_588(0) = '1') else 
        zext_ln43_9_fu_291_p1;
    select_ln43_5_fu_341_p3 <= 
        add_ln43_fu_329_p2 when (icmp_ln43_6_fu_323_p2(0) = '1') else 
        sub_ln43_fu_335_p2;
    select_ln43_5cast_fu_413_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln43_5_reg_621),16));
    select_ln43_6_fu_405_p3 <= 
        trunc_ln43_16_fu_394_p1 when (icmp_ln43_8_fu_381_p2(0) = '1') else 
        select_ln43_fu_398_p3;
    select_ln43_7_fu_421_p3 <= 
        shl_ln43_fu_416_p2 when (icmp_ln43_reg_640(0) = '1') else 
        ap_const_lv16_0;
    select_ln43_fu_398_p3 <= 
        ap_const_lv16_FFFF when (tmp_reg_588_pp0_iter4_reg(0) = '1') else 
        ap_const_lv16_0;
        sext_ln39_5_cast_fu_193_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln39_5),32));

    shl_ln43_fu_416_p2 <= std_logic_vector(shift_left(unsigned(trunc_ln43_15_reg_634),to_integer(unsigned('0' & select_ln43_5cast_fu_413_p1(16-1 downto 0)))));
    sub_ln43_3_fu_295_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(zext_ln43_9_fu_291_p1));
    sub_ln43_4_fu_313_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(zext_ln43_3_fu_281_p1));
    sub_ln43_fu_335_p2 <= std_logic_vector(unsigned(ap_const_lv11_8) - unsigned(trunc_ln43_14_fu_319_p1));
    sum_19_out <= ap_sig_allocacmp_sum(24 - 1 downto 0);

    sum_19_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln41_reg_565_pp0_iter7_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (icmp_ln41_reg_565_pp0_iter7_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            sum_19_out_ap_vld <= ap_const_logic_1;
        else 
            sum_19_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_24_fu_359_p4 <= select_ln43_5_fu_341_p3(10 downto 4);
    trunc_ln41_fu_227_p1 <= ap_sig_allocacmp_j(1 - 1 downto 0);
    trunc_ln43_13_fu_277_p1 <= bitcast_ln716_fu_251_p1(52 - 1 downto 0);
    trunc_ln43_14_fu_319_p1 <= sub_ln43_4_fu_313_p2(11 - 1 downto 0);
    trunc_ln43_15_fu_355_p1 <= select_ln43_4_fu_301_p3(16 - 1 downto 0);
    trunc_ln43_16_fu_394_p1 <= ashr_ln43_fu_389_p2(16 - 1 downto 0);
    trunc_ln43_18_fu_491_p1 <= ap_phi_mux_empty_40_phi_fu_180_p4(16 - 1 downto 0);
    trunc_ln43_fu_255_p1 <= bitcast_ln716_fu_251_p1(63 - 1 downto 0);
    xor_ln43_2_fu_436_p2 <= (icmp_ln43_5_reg_609_pp0_iter5_reg xor ap_const_lv1_1);
    xor_ln43_fu_450_p2 <= (or_ln43_fu_446_p2 xor ap_const_lv1_1);
    zext_ln41_fu_431_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shiftreg869_fu_122),32));
    zext_ln43_12_cast_fu_284_p3 <= (ap_const_lv1_1 & trunc_ln43_13_reg_599);
    zext_ln43_3_fu_281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_reg_594),12));
    zext_ln43_5_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln43_5_reg_621),54));
    zext_ln43_9_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln43_12_cast_fu_284_p3),54));
    zext_ln43_fu_241_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln43_4_fu_231_p4),64));
end behav;
