// ==============================================================
// Generated by Vitis HLS v2024.1.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ecg_classify_trained_ecg_classify_trained_Pipeline_VITIS_LOOP_41_23 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        sext_ln39_11,
        p_cast_cast,
        tmp_117,
        sum_49_out,
        sum_49_out_ap_vld,
        dense_weights_address0,
        dense_weights_ce0,
        dense_weights_q0,
        grp_fu_13213_p_din0,
        grp_fu_13213_p_dout0,
        grp_fu_13213_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [31:0] m_axi_gmem0_WDATA;
output  [3:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [31:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [8:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [23:0] sext_ln39_11;
input  [61:0] p_cast_cast;
input  [4:0] tmp_117;
output  [23:0] sum_49_out;
output   sum_49_out_ap_vld;
output  [12:0] dense_weights_address0;
output   dense_weights_ce0;
input  [31:0] dense_weights_q0;
output  [31:0] grp_fu_13213_p_din0;
input  [63:0] grp_fu_13213_p_dout0;
output   grp_fu_13213_p_ce;

reg ap_idle;
reg m_axi_gmem0_RREADY;
reg sum_49_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln41_reg_567;
reg   [0:0] icmp_ln41_reg_567_pp0_iter4_reg;
reg   [0:0] trunc_ln41_reg_571;
reg   [0:0] trunc_ln41_reg_571_pp0_iter4_reg;
reg    ap_predicate_op70_read_state6;
reg    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_217_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln41_reg_567_pp0_iter1_reg;
reg   [0:0] icmp_ln41_reg_567_pp0_iter2_reg;
reg   [0:0] icmp_ln41_reg_567_pp0_iter3_reg;
reg   [0:0] icmp_ln41_reg_567_pp0_iter5_reg;
reg   [0:0] icmp_ln41_reg_567_pp0_iter6_reg;
reg   [0:0] icmp_ln41_reg_567_pp0_iter7_reg;
wire   [0:0] trunc_ln41_fu_229_p1;
reg   [0:0] trunc_ln41_reg_571_pp0_iter1_reg;
reg   [0:0] trunc_ln41_reg_571_pp0_iter2_reg;
reg   [0:0] trunc_ln41_reg_571_pp0_iter3_reg;
reg   [0:0] trunc_ln41_reg_571_pp0_iter5_reg;
reg   [31:0] dense_weights_load_reg_580;
wire   [62:0] trunc_ln43_fu_257_p1;
reg   [62:0] trunc_ln43_reg_585;
reg   [0:0] tmp_reg_590;
reg   [0:0] tmp_reg_590_pp0_iter4_reg;
reg   [10:0] tmp_s_reg_596;
wire   [51:0] trunc_ln43_1_fu_279_p1;
reg   [51:0] trunc_ln43_1_reg_601;
wire   [53:0] select_ln43_fu_303_p3;
reg   [53:0] select_ln43_reg_606;
wire   [0:0] icmp_ln43_fu_310_p2;
reg   [0:0] icmp_ln43_reg_611;
reg   [0:0] icmp_ln43_reg_611_pp0_iter5_reg;
wire   [0:0] icmp_ln43_1_fu_325_p2;
reg   [0:0] icmp_ln43_1_reg_618;
reg   [0:0] icmp_ln43_1_reg_618_pp0_iter5_reg;
wire   [10:0] select_ln43_1_fu_343_p3;
reg   [10:0] select_ln43_1_reg_623;
wire   [0:0] icmp_ln43_2_fu_351_p2;
reg   [0:0] icmp_ln43_2_reg_630;
reg   [0:0] icmp_ln43_2_reg_630_pp0_iter5_reg;
wire   [15:0] trunc_ln43_3_fu_357_p1;
reg   [15:0] trunc_ln43_3_reg_636;
reg   [15:0] trunc_ln43_3_reg_636_pp0_iter5_reg;
wire   [0:0] icmp_ln43_4_fu_371_p2;
reg   [0:0] icmp_ln43_4_reg_642;
wire   [15:0] select_ln43_3_fu_407_p3;
reg   [15:0] select_ln43_3_reg_647;
wire   [15:0] select_ln43_4_fu_423_p3;
reg   [15:0] select_ln43_4_reg_652;
reg   [31:0] gmem0_addr_read_reg_657;
reg    ap_condition_exit_pp0_iter8_stage0;
reg   [31:0] ap_phi_mux_empty_38_phi_fu_182_p4;
wire   [31:0] ap_phi_reg_pp0_iter6_empty_38_reg_179;
wire   [31:0] zext_ln41_fu_433_p1;
wire   [63:0] zext_ln43_fu_243_p1;
reg   [15:0] shiftreg_fu_124;
wire    ap_loop_init;
reg   [31:0] sum_fu_128;
wire   [31:0] grp_fu_532_p3;
wire  signed [31:0] sext_ln39_11_cast_fu_195_p1;
reg   [31:0] ap_sig_allocacmp_sum_26;
reg   [5:0] j_fu_132;
wire   [5:0] add_ln41_fu_223_p2;
reg   [5:0] ap_sig_allocacmp_j_10;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_block_pp0_stage0_01001;
reg    dense_weights_ce0_local;
wire   [12:0] add_ln43_s_fu_233_p4;
wire   [63:0] bitcast_ln716_fu_253_p1;
wire   [52:0] zext_ln43_18_cast_fu_286_p3;
wire   [53:0] zext_ln43_2_fu_293_p1;
wire   [53:0] sub_ln43_fu_297_p2;
wire   [11:0] zext_ln43_1_fu_283_p1;
wire   [11:0] sub_ln43_1_fu_315_p2;
wire   [10:0] trunc_ln43_2_fu_321_p1;
wire   [10:0] add_ln43_fu_331_p2;
wire   [10:0] sub_ln43_2_fu_337_p2;
wire   [6:0] tmp_22_fu_361_p4;
wire   [53:0] zext_ln43_4_fu_388_p1;
wire   [53:0] ashr_ln43_fu_391_p2;
wire   [0:0] icmp_ln43_3_fu_383_p2;
wire   [15:0] trunc_ln43_4_fu_396_p1;
wire   [15:0] select_ln43_2_fu_400_p3;
wire   [15:0] select_ln43_1cast_fu_415_p1;
wire   [15:0] shl_ln43_fu_418_p2;
wire   [0:0] xor_ln43_fu_438_p2;
wire   [0:0] or_ln43_fu_448_p2;
wire   [0:0] xor_ln43_1_fu_452_p2;
wire   [0:0] and_ln43_fu_443_p2;
wire   [0:0] and_ln43_1_fu_458_p2;
wire   [15:0] ref_tmp_i_i32_1_fu_472_p9;
wire   [2:0] ref_tmp_i_i32_1_fu_472_p10;
wire  signed [15:0] trunc_ln43_6_fu_493_p1;
wire  signed [15:0] ref_tmp_i_i32_1_fu_472_p11;
reg    grp_fu_188_ce;
reg    grp_fu_532_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire  signed [2:0] ref_tmp_i_i32_1_fu_472_p1;
wire   [2:0] ref_tmp_i_i32_1_fu_472_p3;
wire   [2:0] ref_tmp_i_i32_1_fu_472_p5;
wire   [2:0] ref_tmp_i_i32_1_fu_472_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 shiftreg_fu_124 = 16'd0;
#0 sum_fu_128 = 32'd0;
#0 j_fu_132 = 6'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) ecg_classify_trained_sparsemux_9_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_9_3_16_1_1_U31(
    .din0(16'd0),
    .din1(trunc_ln43_3_reg_636_pp0_iter5_reg),
    .din2(select_ln43_3_reg_647),
    .din3(select_ln43_4_reg_652),
    .def(ref_tmp_i_i32_1_fu_472_p9),
    .sel(ref_tmp_i_i32_1_fu_472_p10),
    .dout(ref_tmp_i_i32_1_fu_472_p11)
);

ecg_classify_trained_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln43_6_fu_493_p1),
    .din1(ref_tmp_i_i32_1_fu_472_p11),
    .din2(ap_sig_allocacmp_sum_26),
    .ce(grp_fu_532_ce),
    .dout(grp_fu_532_p3)
);

ecg_classify_trained_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter8_stage0)) begin
            ap_enable_reg_pp0_iter9 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln41_fu_217_p2 == 1'd0))) begin
            j_fu_132 <= add_ln41_fu_223_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_132 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            shiftreg_fu_124 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln41_reg_567_pp0_iter5_reg == 1'd0))) begin
            shiftreg_fu_124 <= {{ap_phi_mux_empty_38_phi_fu_182_p4[31:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_fu_128 <= sext_ln39_11_cast_fu_195_p1;
        end else if ((ap_enable_reg_pp0_iter9 == 1'b1)) begin
            sum_fu_128 <= grp_fu_532_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        dense_weights_load_reg_580 <= dense_weights_q0;
        icmp_ln41_reg_567 <= icmp_ln41_fu_217_p2;
        icmp_ln41_reg_567_pp0_iter1_reg <= icmp_ln41_reg_567;
        trunc_ln41_reg_571 <= trunc_ln41_fu_229_p1;
        trunc_ln41_reg_571_pp0_iter1_reg <= trunc_ln41_reg_571;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        gmem0_addr_read_reg_657 <= m_axi_gmem0_RDATA;
        icmp_ln41_reg_567_pp0_iter2_reg <= icmp_ln41_reg_567_pp0_iter1_reg;
        icmp_ln41_reg_567_pp0_iter3_reg <= icmp_ln41_reg_567_pp0_iter2_reg;
        icmp_ln41_reg_567_pp0_iter4_reg <= icmp_ln41_reg_567_pp0_iter3_reg;
        icmp_ln41_reg_567_pp0_iter5_reg <= icmp_ln41_reg_567_pp0_iter4_reg;
        icmp_ln41_reg_567_pp0_iter6_reg <= icmp_ln41_reg_567_pp0_iter5_reg;
        icmp_ln41_reg_567_pp0_iter7_reg <= icmp_ln41_reg_567_pp0_iter6_reg;
        icmp_ln43_1_reg_618 <= icmp_ln43_1_fu_325_p2;
        icmp_ln43_1_reg_618_pp0_iter5_reg <= icmp_ln43_1_reg_618;
        icmp_ln43_2_reg_630 <= icmp_ln43_2_fu_351_p2;
        icmp_ln43_2_reg_630_pp0_iter5_reg <= icmp_ln43_2_reg_630;
        icmp_ln43_4_reg_642 <= icmp_ln43_4_fu_371_p2;
        icmp_ln43_reg_611 <= icmp_ln43_fu_310_p2;
        icmp_ln43_reg_611_pp0_iter5_reg <= icmp_ln43_reg_611;
        select_ln43_1_reg_623 <= select_ln43_1_fu_343_p3;
        select_ln43_3_reg_647 <= select_ln43_3_fu_407_p3;
        select_ln43_4_reg_652 <= select_ln43_4_fu_423_p3;
        select_ln43_reg_606 <= select_ln43_fu_303_p3;
        tmp_reg_590 <= bitcast_ln716_fu_253_p1[32'd63];
        tmp_reg_590_pp0_iter4_reg <= tmp_reg_590;
        tmp_s_reg_596 <= {{bitcast_ln716_fu_253_p1[62:52]}};
        trunc_ln41_reg_571_pp0_iter2_reg <= trunc_ln41_reg_571_pp0_iter1_reg;
        trunc_ln41_reg_571_pp0_iter3_reg <= trunc_ln41_reg_571_pp0_iter2_reg;
        trunc_ln41_reg_571_pp0_iter4_reg <= trunc_ln41_reg_571_pp0_iter3_reg;
        trunc_ln41_reg_571_pp0_iter5_reg <= trunc_ln41_reg_571_pp0_iter4_reg;
        trunc_ln43_1_reg_601 <= trunc_ln43_1_fu_279_p1;
        trunc_ln43_3_reg_636 <= trunc_ln43_3_fu_357_p1;
        trunc_ln43_3_reg_636_pp0_iter5_reg <= trunc_ln43_3_reg_636;
        trunc_ln43_reg_585 <= trunc_ln43_fu_257_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln41_fu_217_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (icmp_ln41_reg_567_pp0_iter7_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter8_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter8_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln41_reg_567_pp0_iter5_reg == 1'd0)) begin
        if ((trunc_ln41_reg_571_pp0_iter5_reg == 1'd1)) begin
            ap_phi_mux_empty_38_phi_fu_182_p4 = zext_ln41_fu_433_p1;
        end else if ((trunc_ln41_reg_571_pp0_iter5_reg == 1'd0)) begin
            ap_phi_mux_empty_38_phi_fu_182_p4 = gmem0_addr_read_reg_657;
        end else begin
            ap_phi_mux_empty_38_phi_fu_182_p4 = ap_phi_reg_pp0_iter6_empty_38_reg_179;
        end
    end else begin
        ap_phi_mux_empty_38_phi_fu_182_p4 = ap_phi_reg_pp0_iter6_empty_38_reg_179;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_10 = 6'd0;
    end else begin
        ap_sig_allocacmp_j_10 = j_fu_132;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_sum_26 = grp_fu_532_p3;
    end else begin
        ap_sig_allocacmp_sum_26 = sum_fu_128;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        dense_weights_ce0_local = 1'b1;
    end else begin
        dense_weights_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op70_read_state6 == 1'b1))) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_188_ce = 1'b1;
    end else begin
        grp_fu_188_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_532_ce = 1'b1;
    end else begin
        grp_fu_532_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op70_read_state6 == 1'b1))) begin
        m_axi_gmem0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (icmp_ln41_reg_567_pp0_iter7_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_49_out_ap_vld = 1'b1;
    end else begin
        sum_49_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln41_fu_223_p2 = (ap_sig_allocacmp_j_10 + 6'd1);

assign add_ln43_fu_331_p2 = ($signed(trunc_ln43_2_fu_321_p1) + $signed(11'd2040));

assign add_ln43_s_fu_233_p4 = {{{ap_sig_allocacmp_j_10}, {tmp_117}}, {2'd3}};

assign and_ln43_1_fu_458_p2 = (xor_ln43_1_fu_452_p2 & icmp_ln43_1_reg_618_pp0_iter5_reg);

assign and_ln43_fu_443_p2 = (xor_ln43_fu_438_p2 & icmp_ln43_2_reg_630_pp0_iter5_reg);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = ((m_axi_gmem0_RVALID == 1'b0) & (ap_predicate_op70_read_state6 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter6_empty_38_reg_179 = 'bx;

always @ (*) begin
    ap_predicate_op70_read_state6 = ((trunc_ln41_reg_571_pp0_iter4_reg == 1'd0) & (icmp_ln41_reg_567_pp0_iter4_reg == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign ashr_ln43_fu_391_p2 = $signed(select_ln43_reg_606) >>> zext_ln43_4_fu_388_p1;

assign bitcast_ln716_fu_253_p1 = grp_fu_13213_p_dout0;

assign dense_weights_address0 = zext_ln43_fu_243_p1;

assign dense_weights_ce0 = dense_weights_ce0_local;

assign grp_fu_13213_p_ce = grp_fu_188_ce;

assign grp_fu_13213_p_din0 = dense_weights_load_reg_580;

assign icmp_ln41_fu_217_p2 = ((ap_sig_allocacmp_j_10 == 6'd46) ? 1'b1 : 1'b0);

assign icmp_ln43_1_fu_325_p2 = (($signed(sub_ln43_1_fu_315_p2) > $signed(12'd8)) ? 1'b1 : 1'b0);

assign icmp_ln43_2_fu_351_p2 = ((sub_ln43_1_fu_315_p2 == 12'd8) ? 1'b1 : 1'b0);

assign icmp_ln43_3_fu_383_p2 = ((select_ln43_1_reg_623 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln43_4_fu_371_p2 = ((tmp_22_fu_361_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_310_p2 = ((trunc_ln43_reg_585 == 63'd0) ? 1'b1 : 1'b0);

assign m_axi_gmem0_ARADDR = 64'd0;

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = 32'd0;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_ARVALID = 1'b0;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 32'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 4'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign or_ln43_fu_448_p2 = (icmp_ln43_reg_611_pp0_iter5_reg | icmp_ln43_2_reg_630_pp0_iter5_reg);

assign ref_tmp_i_i32_1_fu_472_p10 = {{{icmp_ln43_reg_611_pp0_iter5_reg}, {and_ln43_fu_443_p2}}, {and_ln43_1_fu_458_p2}};

assign ref_tmp_i_i32_1_fu_472_p9 = 'bx;

assign select_ln43_1_fu_343_p3 = ((icmp_ln43_1_fu_325_p2[0:0] == 1'b1) ? add_ln43_fu_331_p2 : sub_ln43_2_fu_337_p2);

assign select_ln43_1cast_fu_415_p1 = select_ln43_1_reg_623;

assign select_ln43_2_fu_400_p3 = ((tmp_reg_590_pp0_iter4_reg[0:0] == 1'b1) ? 16'd65535 : 16'd0);

assign select_ln43_3_fu_407_p3 = ((icmp_ln43_3_fu_383_p2[0:0] == 1'b1) ? trunc_ln43_4_fu_396_p1 : select_ln43_2_fu_400_p3);

assign select_ln43_4_fu_423_p3 = ((icmp_ln43_4_reg_642[0:0] == 1'b1) ? shl_ln43_fu_418_p2 : 16'd0);

assign select_ln43_fu_303_p3 = ((tmp_reg_590[0:0] == 1'b1) ? sub_ln43_fu_297_p2 : zext_ln43_2_fu_293_p1);

assign sext_ln39_11_cast_fu_195_p1 = $signed(sext_ln39_11);

assign shl_ln43_fu_418_p2 = trunc_ln43_3_reg_636 << select_ln43_1cast_fu_415_p1;

assign sub_ln43_1_fu_315_p2 = (12'd1075 - zext_ln43_1_fu_283_p1);

assign sub_ln43_2_fu_337_p2 = (11'd8 - trunc_ln43_2_fu_321_p1);

assign sub_ln43_fu_297_p2 = (54'd0 - zext_ln43_2_fu_293_p1);

assign sum_49_out = ap_sig_allocacmp_sum_26[23:0];

assign tmp_22_fu_361_p4 = {{select_ln43_1_fu_343_p3[10:4]}};

assign trunc_ln41_fu_229_p1 = ap_sig_allocacmp_j_10[0:0];

assign trunc_ln43_1_fu_279_p1 = bitcast_ln716_fu_253_p1[51:0];

assign trunc_ln43_2_fu_321_p1 = sub_ln43_1_fu_315_p2[10:0];

assign trunc_ln43_3_fu_357_p1 = select_ln43_fu_303_p3[15:0];

assign trunc_ln43_4_fu_396_p1 = ashr_ln43_fu_391_p2[15:0];

assign trunc_ln43_6_fu_493_p1 = ap_phi_mux_empty_38_phi_fu_182_p4[15:0];

assign trunc_ln43_fu_257_p1 = bitcast_ln716_fu_253_p1[62:0];

assign xor_ln43_1_fu_452_p2 = (or_ln43_fu_448_p2 ^ 1'd1);

assign xor_ln43_fu_438_p2 = (icmp_ln43_reg_611_pp0_iter5_reg ^ 1'd1);

assign zext_ln41_fu_433_p1 = shiftreg_fu_124;

assign zext_ln43_18_cast_fu_286_p3 = {{1'd1}, {trunc_ln43_1_reg_601}};

assign zext_ln43_1_fu_283_p1 = tmp_s_reg_596;

assign zext_ln43_2_fu_293_p1 = zext_ln43_18_cast_fu_286_p3;

assign zext_ln43_4_fu_388_p1 = select_ln43_1_reg_623;

assign zext_ln43_fu_243_p1 = add_ln43_s_fu_233_p4;

endmodule //ecg_classify_trained_ecg_classify_trained_Pipeline_VITIS_LOOP_41_23
