-- ==============================================================
-- Generated by Vitis HLS v2024.1.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity ecg_classify_trained_dense_2_biases_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of ecg_classify_trained_dense_2_biases_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101110110101100111011101110", 1 => "00111110000101100110110100110111", 2 => "00111101101100010010001111000100", 3 => "10111110001000110010000011011010", 
    4 => "00111101000010000000011000101001", 5 => "00111110101100011000011100011110", 6 => "00111100100001101101101101010001", 7 => "00111110100001101101001001000110", 
    8 => "10111100111001100101000101101110", 9 => "00111101100011111000000001010110", 10 => "00111110010011100011001101101010", 11 => "00111110111010100111010100100101", 
    12 => "00111101010000100001100111101011", 13 => "00111110101001110001110101100000", 14 => "00111101000010100101010110001111", 15 => "00111110001011111100011010010111", 
    16 => "00111101110000000110010010101010", 17 => "00111110100010011001010111001101", 18 => "00111110000001100101100111010001", 19 => "10111100111110100001111000111111", 
    20 => "00111101101010000000100111010101", 21 => "00111110000001100101010100011001", 22 => "00111101010110101011111100110100", 23 => "00111110101100011010110101000011", 
    24 => "00111110101010111110101010110011", 25 => "00111101100110100000110101111000", 26 => "00111101010010101110011001000011", 27 => "00111110010111011101001001101011", 
    28 => "10111110010001010001010011000010", 29 => "00111110001110110011101100110010", 30 => "10111101111011010101111000000111", 31 => "00111111000000010110011100010010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

