-- ==============================================================
-- Generated by Vitis HLS v2024.1.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_classify_trained_ecg_classify_trained_Pipeline_VITIS_LOOP_73_67 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sext_ln71_5 : IN STD_LOGIC_VECTOR (23 downto 0);
    tmp_112 : IN STD_LOGIC_VECTOR (3 downto 0);
    hidden2 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_2 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_3 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_4 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_5 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_6 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_7 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_8 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_9 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_10 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_11 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_12 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_13 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_14 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_15 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_16 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_17 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_18 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_19 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_20 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_21 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_22 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_23 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_24 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_25 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_26 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_27 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_28 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_29 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_30 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_31 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_32 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_33 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_34 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_35 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_36 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_37 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_38 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_39 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_40 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_41 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_42 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_43 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_44 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_45 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_46 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_47 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_48 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_49 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_50 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_51 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_52 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_53 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_54 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_55 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_56 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_57 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_58 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_59 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_60 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_61 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_62 : IN STD_LOGIC_VECTOR (15 downto 0);
    hidden2_63 : IN STD_LOGIC_VECTOR (15 downto 0);
    sum_26_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    sum_26_out_ap_vld : OUT STD_LOGIC;
    dense_2_weights_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    dense_2_weights_ce0 : OUT STD_LOGIC;
    dense_2_weights_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_13213_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_13213_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_13213_p_ce : OUT STD_LOGIC );
end;


architecture behav of ecg_classify_trained_ecg_classify_trained_Pipeline_VITIS_LOOP_73_67 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_433 : STD_LOGIC_VECTOR (11 downto 0) := "010000110011";
    constant ap_const_lv12_8 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_const_lv11_7F8 : STD_LOGIC_VECTOR (10 downto 0) := "11111111000";
    constant ap_const_lv11_8 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv11_36 : STD_LOGIC_VECTOR (10 downto 0) := "00000110110";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln73_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln73_reg_1366 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_reg_1366_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_reg_1366_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_reg_1366_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_reg_1366_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_reg_1366_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_reg_1366_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_reg_1366_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_829_p131 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_17_reg_1375 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_17_reg_1375_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_17_reg_1375_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_17_reg_1375_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_17_reg_1375_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_17_reg_1375_pp0_iter5_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal dense_2_weights_load_reg_1380 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln75_fu_1102_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln75_reg_1385 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_reg_1390 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1390_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_1396 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln75_11_fu_1124_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln75_11_reg_1401 : STD_LOGIC_VECTOR (51 downto 0);
    signal select_ln75_4_fu_1148_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln75_4_reg_1406 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln75_5_fu_1155_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln75_5_reg_1411 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln75_5_reg_1411_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln75_6_fu_1170_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln75_6_reg_1418 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln75_6_reg_1418_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln75_5_fu_1188_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln75_5_reg_1423 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln75_7_fu_1196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln75_7_reg_1430 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln75_7_reg_1430_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln75_13_fu_1202_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln75_13_reg_1436 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln75_13_reg_1436_pp0_iter5_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln75_fu_1216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln75_reg_1442 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln75_6_fu_1246_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln75_6_reg_1447 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln75_7_fu_1262_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln75_7_reg_1452 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_condition_exit_pp0_iter8_stage0 : STD_LOGIC;
    signal zext_ln75_fu_824_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sum_fu_354 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_1343_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln71_5_cast_fu_781_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_sum_16 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal j_fu_358 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln73_fu_804_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_j_7 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal dense_2_weights_ce0_local : STD_LOGIC;
    signal trunc_ln73_3_fu_810_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln75_4_fu_814_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_17_fu_829_p129 : STD_LOGIC_VECTOR (15 downto 0);
    signal bitcast_ln716_fu_1098_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln75_12_cast_fu_1131_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln75_9_fu_1138_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal sub_ln75_3_fu_1142_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln75_3_fu_1128_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln75_4_fu_1160_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln75_12_fu_1166_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln75_fu_1176_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln75_fu_1182_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_16_fu_1206_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln75_5_fu_1227_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln75_fu_1230_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln75_8_fu_1222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln75_14_fu_1235_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln75_fu_1239_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln75_5cast_fu_1254_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln75_fu_1257_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xor_ln75_2_fu_1269_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln75_fu_1279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln75_fu_1283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln75_2_fu_1274_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln75_fu_1289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ref_tmp_i_i274_9_fu_1303_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal ref_tmp_i_i274_9_fu_1303_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal ref_tmp_i_i274_9_fu_1303_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_17_fu_829_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p17 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p19 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p21 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p23 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p25 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p27 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p29 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p31 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p33 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p35 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p37 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p39 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p41 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p43 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p45 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p47 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p49 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p51 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p53 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p55 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p57 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p59 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p61 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p63 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p65 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p67 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p69 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p71 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p73 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p75 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p77 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p79 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p81 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p83 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p85 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p87 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p89 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p91 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p93 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p95 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p97 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p99 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p101 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p103 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p105 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p107 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p109 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p111 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p113 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p115 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p117 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p119 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p121 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p123 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p125 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_829_p127 : STD_LOGIC_VECTOR (5 downto 0);
    signal ref_tmp_i_i274_9_fu_1303_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal ref_tmp_i_i274_9_fu_1303_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ref_tmp_i_i274_9_fu_1303_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal ref_tmp_i_i274_9_fu_1303_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component ecg_classify_trained_fpext_32ns_64_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component ecg_classify_trained_sparsemux_129_6_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (5 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (5 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (5 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (5 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (5 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (5 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (5 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (5 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (5 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (5 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (5 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (5 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (5 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (5 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (5 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (5 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (5 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (5 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (5 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (5 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (5 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (5 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (5 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (5 downto 0);
        din23_WIDTH : INTEGER;
        CASE24 : STD_LOGIC_VECTOR (5 downto 0);
        din24_WIDTH : INTEGER;
        CASE25 : STD_LOGIC_VECTOR (5 downto 0);
        din25_WIDTH : INTEGER;
        CASE26 : STD_LOGIC_VECTOR (5 downto 0);
        din26_WIDTH : INTEGER;
        CASE27 : STD_LOGIC_VECTOR (5 downto 0);
        din27_WIDTH : INTEGER;
        CASE28 : STD_LOGIC_VECTOR (5 downto 0);
        din28_WIDTH : INTEGER;
        CASE29 : STD_LOGIC_VECTOR (5 downto 0);
        din29_WIDTH : INTEGER;
        CASE30 : STD_LOGIC_VECTOR (5 downto 0);
        din30_WIDTH : INTEGER;
        CASE31 : STD_LOGIC_VECTOR (5 downto 0);
        din31_WIDTH : INTEGER;
        CASE32 : STD_LOGIC_VECTOR (5 downto 0);
        din32_WIDTH : INTEGER;
        CASE33 : STD_LOGIC_VECTOR (5 downto 0);
        din33_WIDTH : INTEGER;
        CASE34 : STD_LOGIC_VECTOR (5 downto 0);
        din34_WIDTH : INTEGER;
        CASE35 : STD_LOGIC_VECTOR (5 downto 0);
        din35_WIDTH : INTEGER;
        CASE36 : STD_LOGIC_VECTOR (5 downto 0);
        din36_WIDTH : INTEGER;
        CASE37 : STD_LOGIC_VECTOR (5 downto 0);
        din37_WIDTH : INTEGER;
        CASE38 : STD_LOGIC_VECTOR (5 downto 0);
        din38_WIDTH : INTEGER;
        CASE39 : STD_LOGIC_VECTOR (5 downto 0);
        din39_WIDTH : INTEGER;
        CASE40 : STD_LOGIC_VECTOR (5 downto 0);
        din40_WIDTH : INTEGER;
        CASE41 : STD_LOGIC_VECTOR (5 downto 0);
        din41_WIDTH : INTEGER;
        CASE42 : STD_LOGIC_VECTOR (5 downto 0);
        din42_WIDTH : INTEGER;
        CASE43 : STD_LOGIC_VECTOR (5 downto 0);
        din43_WIDTH : INTEGER;
        CASE44 : STD_LOGIC_VECTOR (5 downto 0);
        din44_WIDTH : INTEGER;
        CASE45 : STD_LOGIC_VECTOR (5 downto 0);
        din45_WIDTH : INTEGER;
        CASE46 : STD_LOGIC_VECTOR (5 downto 0);
        din46_WIDTH : INTEGER;
        CASE47 : STD_LOGIC_VECTOR (5 downto 0);
        din47_WIDTH : INTEGER;
        CASE48 : STD_LOGIC_VECTOR (5 downto 0);
        din48_WIDTH : INTEGER;
        CASE49 : STD_LOGIC_VECTOR (5 downto 0);
        din49_WIDTH : INTEGER;
        CASE50 : STD_LOGIC_VECTOR (5 downto 0);
        din50_WIDTH : INTEGER;
        CASE51 : STD_LOGIC_VECTOR (5 downto 0);
        din51_WIDTH : INTEGER;
        CASE52 : STD_LOGIC_VECTOR (5 downto 0);
        din52_WIDTH : INTEGER;
        CASE53 : STD_LOGIC_VECTOR (5 downto 0);
        din53_WIDTH : INTEGER;
        CASE54 : STD_LOGIC_VECTOR (5 downto 0);
        din54_WIDTH : INTEGER;
        CASE55 : STD_LOGIC_VECTOR (5 downto 0);
        din55_WIDTH : INTEGER;
        CASE56 : STD_LOGIC_VECTOR (5 downto 0);
        din56_WIDTH : INTEGER;
        CASE57 : STD_LOGIC_VECTOR (5 downto 0);
        din57_WIDTH : INTEGER;
        CASE58 : STD_LOGIC_VECTOR (5 downto 0);
        din58_WIDTH : INTEGER;
        CASE59 : STD_LOGIC_VECTOR (5 downto 0);
        din59_WIDTH : INTEGER;
        CASE60 : STD_LOGIC_VECTOR (5 downto 0);
        din60_WIDTH : INTEGER;
        CASE61 : STD_LOGIC_VECTOR (5 downto 0);
        din61_WIDTH : INTEGER;
        CASE62 : STD_LOGIC_VECTOR (5 downto 0);
        din62_WIDTH : INTEGER;
        CASE63 : STD_LOGIC_VECTOR (5 downto 0);
        din63_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (15 downto 0);
        din5 : IN STD_LOGIC_VECTOR (15 downto 0);
        din6 : IN STD_LOGIC_VECTOR (15 downto 0);
        din7 : IN STD_LOGIC_VECTOR (15 downto 0);
        din8 : IN STD_LOGIC_VECTOR (15 downto 0);
        din9 : IN STD_LOGIC_VECTOR (15 downto 0);
        din10 : IN STD_LOGIC_VECTOR (15 downto 0);
        din11 : IN STD_LOGIC_VECTOR (15 downto 0);
        din12 : IN STD_LOGIC_VECTOR (15 downto 0);
        din13 : IN STD_LOGIC_VECTOR (15 downto 0);
        din14 : IN STD_LOGIC_VECTOR (15 downto 0);
        din15 : IN STD_LOGIC_VECTOR (15 downto 0);
        din16 : IN STD_LOGIC_VECTOR (15 downto 0);
        din17 : IN STD_LOGIC_VECTOR (15 downto 0);
        din18 : IN STD_LOGIC_VECTOR (15 downto 0);
        din19 : IN STD_LOGIC_VECTOR (15 downto 0);
        din20 : IN STD_LOGIC_VECTOR (15 downto 0);
        din21 : IN STD_LOGIC_VECTOR (15 downto 0);
        din22 : IN STD_LOGIC_VECTOR (15 downto 0);
        din23 : IN STD_LOGIC_VECTOR (15 downto 0);
        din24 : IN STD_LOGIC_VECTOR (15 downto 0);
        din25 : IN STD_LOGIC_VECTOR (15 downto 0);
        din26 : IN STD_LOGIC_VECTOR (15 downto 0);
        din27 : IN STD_LOGIC_VECTOR (15 downto 0);
        din28 : IN STD_LOGIC_VECTOR (15 downto 0);
        din29 : IN STD_LOGIC_VECTOR (15 downto 0);
        din30 : IN STD_LOGIC_VECTOR (15 downto 0);
        din31 : IN STD_LOGIC_VECTOR (15 downto 0);
        din32 : IN STD_LOGIC_VECTOR (15 downto 0);
        din33 : IN STD_LOGIC_VECTOR (15 downto 0);
        din34 : IN STD_LOGIC_VECTOR (15 downto 0);
        din35 : IN STD_LOGIC_VECTOR (15 downto 0);
        din36 : IN STD_LOGIC_VECTOR (15 downto 0);
        din37 : IN STD_LOGIC_VECTOR (15 downto 0);
        din38 : IN STD_LOGIC_VECTOR (15 downto 0);
        din39 : IN STD_LOGIC_VECTOR (15 downto 0);
        din40 : IN STD_LOGIC_VECTOR (15 downto 0);
        din41 : IN STD_LOGIC_VECTOR (15 downto 0);
        din42 : IN STD_LOGIC_VECTOR (15 downto 0);
        din43 : IN STD_LOGIC_VECTOR (15 downto 0);
        din44 : IN STD_LOGIC_VECTOR (15 downto 0);
        din45 : IN STD_LOGIC_VECTOR (15 downto 0);
        din46 : IN STD_LOGIC_VECTOR (15 downto 0);
        din47 : IN STD_LOGIC_VECTOR (15 downto 0);
        din48 : IN STD_LOGIC_VECTOR (15 downto 0);
        din49 : IN STD_LOGIC_VECTOR (15 downto 0);
        din50 : IN STD_LOGIC_VECTOR (15 downto 0);
        din51 : IN STD_LOGIC_VECTOR (15 downto 0);
        din52 : IN STD_LOGIC_VECTOR (15 downto 0);
        din53 : IN STD_LOGIC_VECTOR (15 downto 0);
        din54 : IN STD_LOGIC_VECTOR (15 downto 0);
        din55 : IN STD_LOGIC_VECTOR (15 downto 0);
        din56 : IN STD_LOGIC_VECTOR (15 downto 0);
        din57 : IN STD_LOGIC_VECTOR (15 downto 0);
        din58 : IN STD_LOGIC_VECTOR (15 downto 0);
        din59 : IN STD_LOGIC_VECTOR (15 downto 0);
        din60 : IN STD_LOGIC_VECTOR (15 downto 0);
        din61 : IN STD_LOGIC_VECTOR (15 downto 0);
        din62 : IN STD_LOGIC_VECTOR (15 downto 0);
        din63 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component ecg_classify_trained_sparsemux_9_3_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component ecg_classify_trained_mac_muladd_16s_16s_32ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_classify_trained_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_129_6_16_1_1_U658 : component ecg_classify_trained_sparsemux_129_6_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000000",
        din0_WIDTH => 16,
        CASE1 => "000001",
        din1_WIDTH => 16,
        CASE2 => "000010",
        din2_WIDTH => 16,
        CASE3 => "000011",
        din3_WIDTH => 16,
        CASE4 => "000100",
        din4_WIDTH => 16,
        CASE5 => "000101",
        din5_WIDTH => 16,
        CASE6 => "000110",
        din6_WIDTH => 16,
        CASE7 => "000111",
        din7_WIDTH => 16,
        CASE8 => "001000",
        din8_WIDTH => 16,
        CASE9 => "001001",
        din9_WIDTH => 16,
        CASE10 => "001010",
        din10_WIDTH => 16,
        CASE11 => "001011",
        din11_WIDTH => 16,
        CASE12 => "001100",
        din12_WIDTH => 16,
        CASE13 => "001101",
        din13_WIDTH => 16,
        CASE14 => "001110",
        din14_WIDTH => 16,
        CASE15 => "001111",
        din15_WIDTH => 16,
        CASE16 => "010000",
        din16_WIDTH => 16,
        CASE17 => "010001",
        din17_WIDTH => 16,
        CASE18 => "010010",
        din18_WIDTH => 16,
        CASE19 => "010011",
        din19_WIDTH => 16,
        CASE20 => "010100",
        din20_WIDTH => 16,
        CASE21 => "010101",
        din21_WIDTH => 16,
        CASE22 => "010110",
        din22_WIDTH => 16,
        CASE23 => "010111",
        din23_WIDTH => 16,
        CASE24 => "011000",
        din24_WIDTH => 16,
        CASE25 => "011001",
        din25_WIDTH => 16,
        CASE26 => "011010",
        din26_WIDTH => 16,
        CASE27 => "011011",
        din27_WIDTH => 16,
        CASE28 => "011100",
        din28_WIDTH => 16,
        CASE29 => "011101",
        din29_WIDTH => 16,
        CASE30 => "011110",
        din30_WIDTH => 16,
        CASE31 => "011111",
        din31_WIDTH => 16,
        CASE32 => "100000",
        din32_WIDTH => 16,
        CASE33 => "100001",
        din33_WIDTH => 16,
        CASE34 => "100010",
        din34_WIDTH => 16,
        CASE35 => "100011",
        din35_WIDTH => 16,
        CASE36 => "100100",
        din36_WIDTH => 16,
        CASE37 => "100101",
        din37_WIDTH => 16,
        CASE38 => "100110",
        din38_WIDTH => 16,
        CASE39 => "100111",
        din39_WIDTH => 16,
        CASE40 => "101000",
        din40_WIDTH => 16,
        CASE41 => "101001",
        din41_WIDTH => 16,
        CASE42 => "101010",
        din42_WIDTH => 16,
        CASE43 => "101011",
        din43_WIDTH => 16,
        CASE44 => "101100",
        din44_WIDTH => 16,
        CASE45 => "101101",
        din45_WIDTH => 16,
        CASE46 => "101110",
        din46_WIDTH => 16,
        CASE47 => "101111",
        din47_WIDTH => 16,
        CASE48 => "110000",
        din48_WIDTH => 16,
        CASE49 => "110001",
        din49_WIDTH => 16,
        CASE50 => "110010",
        din50_WIDTH => 16,
        CASE51 => "110011",
        din51_WIDTH => 16,
        CASE52 => "110100",
        din52_WIDTH => 16,
        CASE53 => "110101",
        din53_WIDTH => 16,
        CASE54 => "110110",
        din54_WIDTH => 16,
        CASE55 => "110111",
        din55_WIDTH => 16,
        CASE56 => "111000",
        din56_WIDTH => 16,
        CASE57 => "111001",
        din57_WIDTH => 16,
        CASE58 => "111010",
        din58_WIDTH => 16,
        CASE59 => "111011",
        din59_WIDTH => 16,
        CASE60 => "111100",
        din60_WIDTH => 16,
        CASE61 => "111101",
        din61_WIDTH => 16,
        CASE62 => "111110",
        din62_WIDTH => 16,
        CASE63 => "111111",
        din63_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 6,
        dout_WIDTH => 16)
    port map (
        din0 => hidden2,
        din1 => hidden2_1,
        din2 => hidden2_2,
        din3 => hidden2_3,
        din4 => hidden2_4,
        din5 => hidden2_5,
        din6 => hidden2_6,
        din7 => hidden2_7,
        din8 => hidden2_8,
        din9 => hidden2_9,
        din10 => hidden2_10,
        din11 => hidden2_11,
        din12 => hidden2_12,
        din13 => hidden2_13,
        din14 => hidden2_14,
        din15 => hidden2_15,
        din16 => hidden2_16,
        din17 => hidden2_17,
        din18 => hidden2_18,
        din19 => hidden2_19,
        din20 => hidden2_20,
        din21 => hidden2_21,
        din22 => hidden2_22,
        din23 => hidden2_23,
        din24 => hidden2_24,
        din25 => hidden2_25,
        din26 => hidden2_26,
        din27 => hidden2_27,
        din28 => hidden2_28,
        din29 => hidden2_29,
        din30 => hidden2_30,
        din31 => hidden2_31,
        din32 => hidden2_32,
        din33 => hidden2_33,
        din34 => hidden2_34,
        din35 => hidden2_35,
        din36 => hidden2_36,
        din37 => hidden2_37,
        din38 => hidden2_38,
        din39 => hidden2_39,
        din40 => hidden2_40,
        din41 => hidden2_41,
        din42 => hidden2_42,
        din43 => hidden2_43,
        din44 => hidden2_44,
        din45 => hidden2_45,
        din46 => hidden2_46,
        din47 => hidden2_47,
        din48 => hidden2_48,
        din49 => hidden2_49,
        din50 => hidden2_50,
        din51 => hidden2_51,
        din52 => hidden2_52,
        din53 => hidden2_53,
        din54 => hidden2_54,
        din55 => hidden2_55,
        din56 => hidden2_56,
        din57 => hidden2_57,
        din58 => hidden2_58,
        din59 => hidden2_59,
        din60 => hidden2_60,
        din61 => hidden2_61,
        din62 => hidden2_62,
        din63 => hidden2_63,
        def => tmp_17_fu_829_p129,
        sel => trunc_ln73_3_fu_810_p1,
        dout => tmp_17_fu_829_p131);

    sparsemux_9_3_16_1_1_U659 : component ecg_classify_trained_sparsemux_9_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 16,
        CASE1 => "010",
        din1_WIDTH => 16,
        CASE2 => "001",
        din2_WIDTH => 16,
        CASE3 => "000",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_0,
        din1 => trunc_ln75_13_reg_1436_pp0_iter5_reg,
        din2 => select_ln75_6_reg_1447,
        din3 => select_ln75_7_reg_1452,
        def => ref_tmp_i_i274_9_fu_1303_p9,
        sel => ref_tmp_i_i274_9_fu_1303_p10,
        dout => ref_tmp_i_i274_9_fu_1303_p11);

    mac_muladd_16s_16s_32ns_32_4_1_U660 : component ecg_classify_trained_mac_muladd_16s_16s_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_17_reg_1375_pp0_iter5_reg,
        din1 => ref_tmp_i_i274_9_fu_1303_p11,
        din2 => ap_sig_allocacmp_sum_16,
        ce => ap_const_logic_1,
        dout => grp_fu_1343_p3);

    flow_control_loop_pipe_sequential_init_U : component ecg_classify_trained_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter8_stage0)) then 
                    ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    j_fu_358_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln73_fu_798_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_358 <= add_ln73_fu_804_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_358 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    sum_fu_354_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    sum_fu_354 <= sext_ln71_5_cast_fu_781_p1;
                elsif ((ap_enable_reg_pp0_iter9 = ap_const_logic_1)) then 
                    sum_fu_354 <= grp_fu_1343_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                dense_2_weights_load_reg_1380 <= dense_2_weights_q0;
                icmp_ln73_reg_1366 <= icmp_ln73_fu_798_p2;
                icmp_ln73_reg_1366_pp0_iter1_reg <= icmp_ln73_reg_1366;
                tmp_17_reg_1375 <= tmp_17_fu_829_p131;
                tmp_17_reg_1375_pp0_iter1_reg <= tmp_17_reg_1375;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                icmp_ln73_reg_1366_pp0_iter2_reg <= icmp_ln73_reg_1366_pp0_iter1_reg;
                icmp_ln73_reg_1366_pp0_iter3_reg <= icmp_ln73_reg_1366_pp0_iter2_reg;
                icmp_ln73_reg_1366_pp0_iter4_reg <= icmp_ln73_reg_1366_pp0_iter3_reg;
                icmp_ln73_reg_1366_pp0_iter5_reg <= icmp_ln73_reg_1366_pp0_iter4_reg;
                icmp_ln73_reg_1366_pp0_iter6_reg <= icmp_ln73_reg_1366_pp0_iter5_reg;
                icmp_ln73_reg_1366_pp0_iter7_reg <= icmp_ln73_reg_1366_pp0_iter6_reg;
                icmp_ln75_5_reg_1411 <= icmp_ln75_5_fu_1155_p2;
                icmp_ln75_5_reg_1411_pp0_iter5_reg <= icmp_ln75_5_reg_1411;
                icmp_ln75_6_reg_1418 <= icmp_ln75_6_fu_1170_p2;
                icmp_ln75_6_reg_1418_pp0_iter5_reg <= icmp_ln75_6_reg_1418;
                icmp_ln75_7_reg_1430 <= icmp_ln75_7_fu_1196_p2;
                icmp_ln75_7_reg_1430_pp0_iter5_reg <= icmp_ln75_7_reg_1430;
                icmp_ln75_reg_1442 <= icmp_ln75_fu_1216_p2;
                select_ln75_4_reg_1406 <= select_ln75_4_fu_1148_p3;
                select_ln75_5_reg_1423 <= select_ln75_5_fu_1188_p3;
                select_ln75_6_reg_1447 <= select_ln75_6_fu_1246_p3;
                select_ln75_7_reg_1452 <= select_ln75_7_fu_1262_p3;
                tmp_17_reg_1375_pp0_iter2_reg <= tmp_17_reg_1375_pp0_iter1_reg;
                tmp_17_reg_1375_pp0_iter3_reg <= tmp_17_reg_1375_pp0_iter2_reg;
                tmp_17_reg_1375_pp0_iter4_reg <= tmp_17_reg_1375_pp0_iter3_reg;
                tmp_17_reg_1375_pp0_iter5_reg <= tmp_17_reg_1375_pp0_iter4_reg;
                tmp_reg_1390 <= bitcast_ln716_fu_1098_p1(63 downto 63);
                tmp_reg_1390_pp0_iter4_reg <= tmp_reg_1390;
                tmp_s_reg_1396 <= bitcast_ln716_fu_1098_p1(62 downto 52);
                trunc_ln75_11_reg_1401 <= trunc_ln75_11_fu_1124_p1;
                trunc_ln75_13_reg_1436 <= trunc_ln75_13_fu_1202_p1;
                trunc_ln75_13_reg_1436_pp0_iter5_reg <= trunc_ln75_13_reg_1436;
                trunc_ln75_reg_1385 <= trunc_ln75_fu_1102_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln73_fu_804_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_7) + unsigned(ap_const_lv7_1));
    add_ln75_4_fu_814_p4 <= ((trunc_ln73_3_fu_810_p1 & tmp_112) & ap_const_lv1_1);
    add_ln75_fu_1176_p2 <= std_logic_vector(unsigned(trunc_ln75_12_fu_1166_p1) + unsigned(ap_const_lv11_7F8));
    and_ln75_2_fu_1274_p2 <= (xor_ln75_2_fu_1269_p2 and icmp_ln75_7_reg_1430_pp0_iter5_reg);
    and_ln75_fu_1289_p2 <= (xor_ln75_fu_1283_p2 and icmp_ln75_6_reg_1418_pp0_iter5_reg);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln73_fu_798_p2)
    begin
        if (((icmp_ln73_fu_798_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter8_stage0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_subdone, icmp_ln73_reg_1366_pp0_iter7_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (icmp_ln73_reg_1366_pp0_iter7_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter8_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter8_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter8_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_7_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, j_fu_358)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_7 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_j_7 <= j_fu_358;
        end if; 
    end process;


    ap_sig_allocacmp_sum_16_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0, sum_fu_354, grp_fu_1343_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            ap_sig_allocacmp_sum_16 <= grp_fu_1343_p3;
        else 
            ap_sig_allocacmp_sum_16 <= sum_fu_354;
        end if; 
    end process;

    ashr_ln75_fu_1230_p2 <= std_logic_vector(shift_right(signed(select_ln75_4_reg_1406),to_integer(unsigned('0' & zext_ln75_5_fu_1227_p1(31-1 downto 0)))));
    bitcast_ln716_fu_1098_p1 <= grp_fu_13213_p_dout0;
    dense_2_weights_address0 <= zext_ln75_fu_824_p1(11 - 1 downto 0);
    dense_2_weights_ce0 <= dense_2_weights_ce0_local;

    dense_2_weights_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dense_2_weights_ce0_local <= ap_const_logic_1;
        else 
            dense_2_weights_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_13213_p_ce <= ap_const_logic_1;
    grp_fu_13213_p_din0 <= dense_2_weights_load_reg_1380;
    icmp_ln73_fu_798_p2 <= "1" when (ap_sig_allocacmp_j_7 = ap_const_lv7_40) else "0";
    icmp_ln75_5_fu_1155_p2 <= "1" when (trunc_ln75_reg_1385 = ap_const_lv63_0) else "0";
    icmp_ln75_6_fu_1170_p2 <= "1" when (signed(sub_ln75_4_fu_1160_p2) > signed(ap_const_lv12_8)) else "0";
    icmp_ln75_7_fu_1196_p2 <= "1" when (sub_ln75_4_fu_1160_p2 = ap_const_lv12_8) else "0";
    icmp_ln75_8_fu_1222_p2 <= "1" when (unsigned(select_ln75_5_reg_1423) < unsigned(ap_const_lv11_36)) else "0";
    icmp_ln75_fu_1216_p2 <= "1" when (tmp_16_fu_1206_p4 = ap_const_lv7_0) else "0";
    or_ln75_fu_1279_p2 <= (icmp_ln75_7_reg_1430_pp0_iter5_reg or icmp_ln75_5_reg_1411_pp0_iter5_reg);
    ref_tmp_i_i274_9_fu_1303_p10 <= ((icmp_ln75_5_reg_1411_pp0_iter5_reg & and_ln75_2_fu_1274_p2) & and_ln75_fu_1289_p2);
    ref_tmp_i_i274_9_fu_1303_p9 <= "XXXXXXXXXXXXXXXX";
    select_ln75_4_fu_1148_p3 <= 
        sub_ln75_3_fu_1142_p2 when (tmp_reg_1390(0) = '1') else 
        zext_ln75_9_fu_1138_p1;
    select_ln75_5_fu_1188_p3 <= 
        add_ln75_fu_1176_p2 when (icmp_ln75_6_fu_1170_p2(0) = '1') else 
        sub_ln75_fu_1182_p2;
    select_ln75_5cast_fu_1254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln75_5_reg_1423),16));
    select_ln75_6_fu_1246_p3 <= 
        trunc_ln75_14_fu_1235_p1 when (icmp_ln75_8_fu_1222_p2(0) = '1') else 
        select_ln75_fu_1239_p3;
    select_ln75_7_fu_1262_p3 <= 
        shl_ln75_fu_1257_p2 when (icmp_ln75_reg_1442(0) = '1') else 
        ap_const_lv16_0;
    select_ln75_fu_1239_p3 <= 
        ap_const_lv16_FFFF when (tmp_reg_1390_pp0_iter4_reg(0) = '1') else 
        ap_const_lv16_0;
        sext_ln71_5_cast_fu_781_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln71_5),32));

    shl_ln75_fu_1257_p2 <= std_logic_vector(shift_left(unsigned(trunc_ln75_13_reg_1436),to_integer(unsigned('0' & select_ln75_5cast_fu_1254_p1(16-1 downto 0)))));
    sub_ln75_3_fu_1142_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(zext_ln75_9_fu_1138_p1));
    sub_ln75_4_fu_1160_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(zext_ln75_3_fu_1128_p1));
    sub_ln75_fu_1182_p2 <= std_logic_vector(unsigned(ap_const_lv11_8) - unsigned(trunc_ln75_12_fu_1166_p1));
    sum_26_out <= ap_sig_allocacmp_sum_16(24 - 1 downto 0);

    sum_26_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln73_reg_1366_pp0_iter7_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (icmp_ln73_reg_1366_pp0_iter7_reg = ap_const_lv1_1))) then 
            sum_26_out_ap_vld <= ap_const_logic_1;
        else 
            sum_26_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_16_fu_1206_p4 <= select_ln75_5_fu_1188_p3(10 downto 4);
    tmp_17_fu_829_p129 <= "XXXXXXXXXXXXXXXX";
    trunc_ln73_3_fu_810_p1 <= ap_sig_allocacmp_j_7(6 - 1 downto 0);
    trunc_ln75_11_fu_1124_p1 <= bitcast_ln716_fu_1098_p1(52 - 1 downto 0);
    trunc_ln75_12_fu_1166_p1 <= sub_ln75_4_fu_1160_p2(11 - 1 downto 0);
    trunc_ln75_13_fu_1202_p1 <= select_ln75_4_fu_1148_p3(16 - 1 downto 0);
    trunc_ln75_14_fu_1235_p1 <= ashr_ln75_fu_1230_p2(16 - 1 downto 0);
    trunc_ln75_fu_1102_p1 <= bitcast_ln716_fu_1098_p1(63 - 1 downto 0);
    xor_ln75_2_fu_1269_p2 <= (icmp_ln75_5_reg_1411_pp0_iter5_reg xor ap_const_lv1_1);
    xor_ln75_fu_1283_p2 <= (or_ln75_fu_1279_p2 xor ap_const_lv1_1);
    zext_ln75_12_cast_fu_1131_p3 <= (ap_const_lv1_1 & trunc_ln75_11_reg_1401);
    zext_ln75_3_fu_1128_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_reg_1396),12));
    zext_ln75_5_fu_1227_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln75_5_reg_1423),54));
    zext_ln75_9_fu_1138_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln75_12_cast_fu_1131_p3),54));
    zext_ln75_fu_824_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln75_4_fu_814_p4),64));
end behav;
