// ==============================================================
// Generated by Vitis HLS v2024.1.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ecg_classify_trained_ecg_classify_trained_Pipeline_VITIS_LOOP_57_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln55_2,
        zext_ln53_1,
        hidden1,
        hidden1_1,
        hidden1_2,
        hidden1_3,
        hidden1_4,
        hidden1_5,
        hidden1_6,
        hidden1_7,
        hidden1_8,
        hidden1_9,
        hidden1_10,
        hidden1_11,
        hidden1_12,
        hidden1_13,
        hidden1_14,
        hidden1_15,
        hidden1_16,
        hidden1_17,
        hidden1_18,
        hidden1_19,
        hidden1_20,
        hidden1_21,
        hidden1_22,
        hidden1_23,
        hidden1_24,
        hidden1_25,
        hidden1_26,
        hidden1_27,
        hidden1_28,
        hidden1_29,
        hidden1_30,
        hidden1_31,
        hidden1_32,
        hidden1_33,
        hidden1_34,
        hidden1_35,
        hidden1_36,
        hidden1_37,
        hidden1_38,
        hidden1_39,
        hidden1_40,
        hidden1_41,
        hidden1_42,
        hidden1_43,
        hidden1_44,
        hidden1_45,
        hidden1_46,
        hidden1_47,
        hidden1_48,
        hidden1_49,
        hidden1_50,
        hidden1_51,
        hidden1_52,
        hidden1_53,
        hidden1_54,
        hidden1_55,
        hidden1_56,
        hidden1_57,
        hidden1_58,
        hidden1_59,
        hidden1_60,
        hidden1_61,
        hidden1_62,
        hidden1_63,
        hidden1_64,
        hidden1_65,
        hidden1_66,
        hidden1_67,
        hidden1_68,
        hidden1_69,
        hidden1_70,
        hidden1_71,
        hidden1_72,
        hidden1_73,
        hidden1_74,
        hidden1_75,
        hidden1_76,
        hidden1_77,
        hidden1_78,
        hidden1_79,
        hidden1_80,
        hidden1_81,
        hidden1_82,
        hidden1_83,
        hidden1_84,
        hidden1_85,
        hidden1_86,
        hidden1_87,
        hidden1_88,
        hidden1_89,
        hidden1_90,
        hidden1_91,
        hidden1_92,
        hidden1_93,
        hidden1_94,
        hidden1_95,
        hidden1_96,
        hidden1_97,
        hidden1_98,
        hidden1_99,
        hidden1_100,
        hidden1_101,
        hidden1_102,
        hidden1_103,
        hidden1_104,
        hidden1_105,
        hidden1_106,
        hidden1_107,
        hidden1_108,
        hidden1_109,
        hidden1_110,
        hidden1_111,
        hidden1_112,
        hidden1_113,
        hidden1_114,
        hidden1_115,
        hidden1_116,
        hidden1_117,
        hidden1_118,
        hidden1_119,
        hidden1_120,
        hidden1_121,
        hidden1_122,
        hidden1_123,
        hidden1_124,
        hidden1_125,
        hidden1_126,
        hidden1_127,
        sum_6_out,
        sum_6_out_ap_vld,
        dense_1_weights_address0,
        dense_1_weights_ce0,
        dense_1_weights_q0,
        grp_fu_13213_p_din0,
        grp_fu_13213_p_dout0,
        grp_fu_13213_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] sext_ln55_2;
input  [5:0] zext_ln53_1;
input  [15:0] hidden1;
input  [15:0] hidden1_1;
input  [15:0] hidden1_2;
input  [15:0] hidden1_3;
input  [15:0] hidden1_4;
input  [15:0] hidden1_5;
input  [15:0] hidden1_6;
input  [15:0] hidden1_7;
input  [15:0] hidden1_8;
input  [15:0] hidden1_9;
input  [15:0] hidden1_10;
input  [15:0] hidden1_11;
input  [15:0] hidden1_12;
input  [15:0] hidden1_13;
input  [15:0] hidden1_14;
input  [15:0] hidden1_15;
input  [15:0] hidden1_16;
input  [15:0] hidden1_17;
input  [15:0] hidden1_18;
input  [15:0] hidden1_19;
input  [15:0] hidden1_20;
input  [15:0] hidden1_21;
input  [15:0] hidden1_22;
input  [15:0] hidden1_23;
input  [15:0] hidden1_24;
input  [15:0] hidden1_25;
input  [15:0] hidden1_26;
input  [15:0] hidden1_27;
input  [15:0] hidden1_28;
input  [15:0] hidden1_29;
input  [15:0] hidden1_30;
input  [15:0] hidden1_31;
input  [15:0] hidden1_32;
input  [15:0] hidden1_33;
input  [15:0] hidden1_34;
input  [15:0] hidden1_35;
input  [15:0] hidden1_36;
input  [15:0] hidden1_37;
input  [15:0] hidden1_38;
input  [15:0] hidden1_39;
input  [15:0] hidden1_40;
input  [15:0] hidden1_41;
input  [15:0] hidden1_42;
input  [15:0] hidden1_43;
input  [15:0] hidden1_44;
input  [15:0] hidden1_45;
input  [15:0] hidden1_46;
input  [15:0] hidden1_47;
input  [15:0] hidden1_48;
input  [15:0] hidden1_49;
input  [15:0] hidden1_50;
input  [15:0] hidden1_51;
input  [15:0] hidden1_52;
input  [15:0] hidden1_53;
input  [15:0] hidden1_54;
input  [15:0] hidden1_55;
input  [15:0] hidden1_56;
input  [15:0] hidden1_57;
input  [15:0] hidden1_58;
input  [15:0] hidden1_59;
input  [15:0] hidden1_60;
input  [15:0] hidden1_61;
input  [15:0] hidden1_62;
input  [15:0] hidden1_63;
input  [15:0] hidden1_64;
input  [15:0] hidden1_65;
input  [15:0] hidden1_66;
input  [15:0] hidden1_67;
input  [15:0] hidden1_68;
input  [15:0] hidden1_69;
input  [15:0] hidden1_70;
input  [15:0] hidden1_71;
input  [15:0] hidden1_72;
input  [15:0] hidden1_73;
input  [15:0] hidden1_74;
input  [15:0] hidden1_75;
input  [15:0] hidden1_76;
input  [15:0] hidden1_77;
input  [15:0] hidden1_78;
input  [15:0] hidden1_79;
input  [15:0] hidden1_80;
input  [15:0] hidden1_81;
input  [15:0] hidden1_82;
input  [15:0] hidden1_83;
input  [15:0] hidden1_84;
input  [15:0] hidden1_85;
input  [15:0] hidden1_86;
input  [15:0] hidden1_87;
input  [15:0] hidden1_88;
input  [15:0] hidden1_89;
input  [15:0] hidden1_90;
input  [15:0] hidden1_91;
input  [15:0] hidden1_92;
input  [15:0] hidden1_93;
input  [15:0] hidden1_94;
input  [15:0] hidden1_95;
input  [15:0] hidden1_96;
input  [15:0] hidden1_97;
input  [15:0] hidden1_98;
input  [15:0] hidden1_99;
input  [15:0] hidden1_100;
input  [15:0] hidden1_101;
input  [15:0] hidden1_102;
input  [15:0] hidden1_103;
input  [15:0] hidden1_104;
input  [15:0] hidden1_105;
input  [15:0] hidden1_106;
input  [15:0] hidden1_107;
input  [15:0] hidden1_108;
input  [15:0] hidden1_109;
input  [15:0] hidden1_110;
input  [15:0] hidden1_111;
input  [15:0] hidden1_112;
input  [15:0] hidden1_113;
input  [15:0] hidden1_114;
input  [15:0] hidden1_115;
input  [15:0] hidden1_116;
input  [15:0] hidden1_117;
input  [15:0] hidden1_118;
input  [15:0] hidden1_119;
input  [15:0] hidden1_120;
input  [15:0] hidden1_121;
input  [15:0] hidden1_122;
input  [15:0] hidden1_123;
input  [15:0] hidden1_124;
input  [15:0] hidden1_125;
input  [15:0] hidden1_126;
input  [15:0] hidden1_127;
output  [23:0] sum_6_out;
output   sum_6_out_ap_vld;
output  [12:0] dense_1_weights_address0;
output   dense_1_weights_ce0;
input  [31:0] dense_1_weights_q0;
output  [31:0] grp_fu_13213_p_din0;
input  [63:0] grp_fu_13213_p_dout0;
output   grp_fu_13213_p_ce;

reg ap_idle;
reg sum_6_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln57_fu_1438_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln57_reg_2262;
reg   [0:0] icmp_ln57_reg_2262_pp0_iter1_reg;
reg   [0:0] icmp_ln57_reg_2262_pp0_iter2_reg;
reg   [0:0] icmp_ln57_reg_2262_pp0_iter3_reg;
reg   [0:0] icmp_ln57_reg_2262_pp0_iter4_reg;
reg   [0:0] icmp_ln57_reg_2262_pp0_iter5_reg;
reg   [0:0] icmp_ln57_reg_2262_pp0_iter6_reg;
reg   [0:0] icmp_ln57_reg_2262_pp0_iter7_reg;
wire   [15:0] tmp_22_fu_1467_p259;
reg   [15:0] tmp_22_reg_2271;
reg   [15:0] tmp_22_reg_2271_pp0_iter1_reg;
reg   [15:0] tmp_22_reg_2271_pp0_iter2_reg;
reg   [15:0] tmp_22_reg_2271_pp0_iter3_reg;
reg   [15:0] tmp_22_reg_2271_pp0_iter4_reg;
reg  signed [15:0] tmp_22_reg_2271_pp0_iter5_reg;
reg   [31:0] dense_1_weights_load_reg_2276;
wire   [62:0] trunc_ln59_fu_1996_p1;
reg   [62:0] trunc_ln59_reg_2281;
reg   [0:0] tmp_reg_2286;
reg   [0:0] tmp_reg_2286_pp0_iter4_reg;
reg   [10:0] tmp_s_reg_2292;
wire   [51:0] trunc_ln59_16_fu_2018_p1;
reg   [51:0] trunc_ln59_16_reg_2297;
wire   [53:0] select_ln59_fu_2042_p3;
reg   [53:0] select_ln59_reg_2302;
wire   [0:0] icmp_ln59_fu_2049_p2;
reg   [0:0] icmp_ln59_reg_2307;
reg   [0:0] icmp_ln59_reg_2307_pp0_iter5_reg;
wire   [10:0] select_ln59_1_fu_2082_p3;
reg   [10:0] select_ln59_1_reg_2313;
wire   [0:0] icmp_ln59_2_fu_2090_p2;
reg   [0:0] icmp_ln59_2_reg_2320;
reg   [0:0] icmp_ln59_2_reg_2320_pp0_iter5_reg;
wire   [15:0] trunc_ln59_18_fu_2096_p1;
reg   [15:0] trunc_ln59_18_reg_2325;
reg   [15:0] trunc_ln59_18_reg_2325_pp0_iter5_reg;
wire   [0:0] icmp_ln59_9_fu_2110_p2;
reg   [0:0] icmp_ln59_9_reg_2331;
wire   [0:0] and_ln59_1_fu_2128_p2;
reg   [0:0] and_ln59_1_reg_2336;
reg   [0:0] and_ln59_1_reg_2336_pp0_iter5_reg;
wire   [15:0] select_ln59_2_fu_2158_p3;
reg   [15:0] select_ln59_2_reg_2341;
wire   [15:0] select_ln59_3_fu_2174_p3;
reg   [15:0] select_ln59_3_reg_2346;
reg    ap_condition_exit_pp0_iter8_stage0;
wire   [63:0] zext_ln59_1_fu_1462_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] sum_6_fu_610;
wire   [31:0] grp_fu_2239_p3;
wire  signed [31:0] sext_ln55_2_cast_fu_1421_p1;
reg   [31:0] ap_sig_allocacmp_sum;
wire    ap_loop_init;
reg   [7:0] j_2_fu_614;
wire   [7:0] add_ln57_fu_1444_p2;
reg   [7:0] ap_sig_allocacmp_j;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
wire    ap_block_pp0_stage0_01001;
reg    dense_1_weights_ce0_local;
wire   [6:0] trunc_ln57_4_fu_1450_p1;
wire   [12:0] add_ln_fu_1454_p3;
wire   [15:0] tmp_22_fu_1467_p257;
wire   [63:0] bitcast_ln716_fu_1992_p1;
wire   [52:0] zext_ln59_4_cast_fu_2025_p3;
wire   [53:0] zext_ln59_11_fu_2032_p1;
wire   [53:0] sub_ln59_fu_2036_p2;
wire   [11:0] zext_ln59_fu_2022_p1;
wire   [11:0] sub_ln59_1_fu_2054_p2;
wire   [10:0] trunc_ln59_17_fu_2060_p1;
wire   [0:0] icmp_ln59_1_fu_2064_p2;
wire   [10:0] add_ln59_1_fu_2070_p2;
wire   [10:0] sub_ln59_2_fu_2076_p2;
wire   [6:0] tmp_21_fu_2100_p4;
wire   [0:0] or_ln59_fu_2116_p2;
wire   [0:0] xor_ln59_1_fu_2122_p2;
wire   [53:0] zext_ln59_2_fu_2139_p1;
wire   [53:0] ashr_ln59_fu_2142_p2;
wire   [0:0] icmp_ln59_3_fu_2134_p2;
wire   [15:0] trunc_ln59_19_fu_2147_p1;
wire   [15:0] select_ln59_9_fu_2151_p3;
wire   [15:0] select_ln59_1cast_fu_2166_p1;
wire   [15:0] shl_ln59_fu_2169_p2;
wire   [0:0] xor_ln59_fu_2181_p2;
wire   [0:0] and_ln59_fu_2186_p2;
wire   [15:0] ref_tmp_i_i312_4_fu_2199_p9;
wire   [2:0] ref_tmp_i_i312_4_fu_2199_p10;
wire  signed [15:0] ref_tmp_i_i312_4_fu_2199_p11;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [6:0] tmp_22_fu_1467_p1;
wire   [6:0] tmp_22_fu_1467_p3;
wire   [6:0] tmp_22_fu_1467_p5;
wire   [6:0] tmp_22_fu_1467_p7;
wire   [6:0] tmp_22_fu_1467_p9;
wire   [6:0] tmp_22_fu_1467_p11;
wire   [6:0] tmp_22_fu_1467_p13;
wire   [6:0] tmp_22_fu_1467_p15;
wire   [6:0] tmp_22_fu_1467_p17;
wire   [6:0] tmp_22_fu_1467_p19;
wire   [6:0] tmp_22_fu_1467_p21;
wire   [6:0] tmp_22_fu_1467_p23;
wire   [6:0] tmp_22_fu_1467_p25;
wire   [6:0] tmp_22_fu_1467_p27;
wire   [6:0] tmp_22_fu_1467_p29;
wire   [6:0] tmp_22_fu_1467_p31;
wire   [6:0] tmp_22_fu_1467_p33;
wire   [6:0] tmp_22_fu_1467_p35;
wire   [6:0] tmp_22_fu_1467_p37;
wire   [6:0] tmp_22_fu_1467_p39;
wire   [6:0] tmp_22_fu_1467_p41;
wire   [6:0] tmp_22_fu_1467_p43;
wire   [6:0] tmp_22_fu_1467_p45;
wire   [6:0] tmp_22_fu_1467_p47;
wire   [6:0] tmp_22_fu_1467_p49;
wire   [6:0] tmp_22_fu_1467_p51;
wire   [6:0] tmp_22_fu_1467_p53;
wire   [6:0] tmp_22_fu_1467_p55;
wire   [6:0] tmp_22_fu_1467_p57;
wire   [6:0] tmp_22_fu_1467_p59;
wire   [6:0] tmp_22_fu_1467_p61;
wire   [6:0] tmp_22_fu_1467_p63;
wire   [6:0] tmp_22_fu_1467_p65;
wire   [6:0] tmp_22_fu_1467_p67;
wire   [6:0] tmp_22_fu_1467_p69;
wire   [6:0] tmp_22_fu_1467_p71;
wire   [6:0] tmp_22_fu_1467_p73;
wire   [6:0] tmp_22_fu_1467_p75;
wire   [6:0] tmp_22_fu_1467_p77;
wire   [6:0] tmp_22_fu_1467_p79;
wire   [6:0] tmp_22_fu_1467_p81;
wire   [6:0] tmp_22_fu_1467_p83;
wire   [6:0] tmp_22_fu_1467_p85;
wire   [6:0] tmp_22_fu_1467_p87;
wire   [6:0] tmp_22_fu_1467_p89;
wire   [6:0] tmp_22_fu_1467_p91;
wire   [6:0] tmp_22_fu_1467_p93;
wire   [6:0] tmp_22_fu_1467_p95;
wire   [6:0] tmp_22_fu_1467_p97;
wire   [6:0] tmp_22_fu_1467_p99;
wire   [6:0] tmp_22_fu_1467_p101;
wire   [6:0] tmp_22_fu_1467_p103;
wire   [6:0] tmp_22_fu_1467_p105;
wire   [6:0] tmp_22_fu_1467_p107;
wire   [6:0] tmp_22_fu_1467_p109;
wire   [6:0] tmp_22_fu_1467_p111;
wire   [6:0] tmp_22_fu_1467_p113;
wire   [6:0] tmp_22_fu_1467_p115;
wire   [6:0] tmp_22_fu_1467_p117;
wire   [6:0] tmp_22_fu_1467_p119;
wire   [6:0] tmp_22_fu_1467_p121;
wire   [6:0] tmp_22_fu_1467_p123;
wire   [6:0] tmp_22_fu_1467_p125;
wire   [6:0] tmp_22_fu_1467_p127;
wire  signed [6:0] tmp_22_fu_1467_p129;
wire  signed [6:0] tmp_22_fu_1467_p131;
wire  signed [6:0] tmp_22_fu_1467_p133;
wire  signed [6:0] tmp_22_fu_1467_p135;
wire  signed [6:0] tmp_22_fu_1467_p137;
wire  signed [6:0] tmp_22_fu_1467_p139;
wire  signed [6:0] tmp_22_fu_1467_p141;
wire  signed [6:0] tmp_22_fu_1467_p143;
wire  signed [6:0] tmp_22_fu_1467_p145;
wire  signed [6:0] tmp_22_fu_1467_p147;
wire  signed [6:0] tmp_22_fu_1467_p149;
wire  signed [6:0] tmp_22_fu_1467_p151;
wire  signed [6:0] tmp_22_fu_1467_p153;
wire  signed [6:0] tmp_22_fu_1467_p155;
wire  signed [6:0] tmp_22_fu_1467_p157;
wire  signed [6:0] tmp_22_fu_1467_p159;
wire  signed [6:0] tmp_22_fu_1467_p161;
wire  signed [6:0] tmp_22_fu_1467_p163;
wire  signed [6:0] tmp_22_fu_1467_p165;
wire  signed [6:0] tmp_22_fu_1467_p167;
wire  signed [6:0] tmp_22_fu_1467_p169;
wire  signed [6:0] tmp_22_fu_1467_p171;
wire  signed [6:0] tmp_22_fu_1467_p173;
wire  signed [6:0] tmp_22_fu_1467_p175;
wire  signed [6:0] tmp_22_fu_1467_p177;
wire  signed [6:0] tmp_22_fu_1467_p179;
wire  signed [6:0] tmp_22_fu_1467_p181;
wire  signed [6:0] tmp_22_fu_1467_p183;
wire  signed [6:0] tmp_22_fu_1467_p185;
wire  signed [6:0] tmp_22_fu_1467_p187;
wire  signed [6:0] tmp_22_fu_1467_p189;
wire  signed [6:0] tmp_22_fu_1467_p191;
wire  signed [6:0] tmp_22_fu_1467_p193;
wire  signed [6:0] tmp_22_fu_1467_p195;
wire  signed [6:0] tmp_22_fu_1467_p197;
wire  signed [6:0] tmp_22_fu_1467_p199;
wire  signed [6:0] tmp_22_fu_1467_p201;
wire  signed [6:0] tmp_22_fu_1467_p203;
wire  signed [6:0] tmp_22_fu_1467_p205;
wire  signed [6:0] tmp_22_fu_1467_p207;
wire  signed [6:0] tmp_22_fu_1467_p209;
wire  signed [6:0] tmp_22_fu_1467_p211;
wire  signed [6:0] tmp_22_fu_1467_p213;
wire  signed [6:0] tmp_22_fu_1467_p215;
wire  signed [6:0] tmp_22_fu_1467_p217;
wire  signed [6:0] tmp_22_fu_1467_p219;
wire  signed [6:0] tmp_22_fu_1467_p221;
wire  signed [6:0] tmp_22_fu_1467_p223;
wire  signed [6:0] tmp_22_fu_1467_p225;
wire  signed [6:0] tmp_22_fu_1467_p227;
wire  signed [6:0] tmp_22_fu_1467_p229;
wire  signed [6:0] tmp_22_fu_1467_p231;
wire  signed [6:0] tmp_22_fu_1467_p233;
wire  signed [6:0] tmp_22_fu_1467_p235;
wire  signed [6:0] tmp_22_fu_1467_p237;
wire  signed [6:0] tmp_22_fu_1467_p239;
wire  signed [6:0] tmp_22_fu_1467_p241;
wire  signed [6:0] tmp_22_fu_1467_p243;
wire  signed [6:0] tmp_22_fu_1467_p245;
wire  signed [6:0] tmp_22_fu_1467_p247;
wire  signed [6:0] tmp_22_fu_1467_p249;
wire  signed [6:0] tmp_22_fu_1467_p251;
wire  signed [6:0] tmp_22_fu_1467_p253;
wire  signed [6:0] tmp_22_fu_1467_p255;
wire  signed [2:0] ref_tmp_i_i312_4_fu_2199_p1;
wire   [2:0] ref_tmp_i_i312_4_fu_2199_p3;
wire   [2:0] ref_tmp_i_i312_4_fu_2199_p5;
wire   [2:0] ref_tmp_i_i312_4_fu_2199_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 sum_6_fu_610 = 32'd0;
#0 j_2_fu_614 = 8'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) ecg_classify_trained_sparsemux_257_7_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 7'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 7'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 7'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 7'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 7'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 7'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 7'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 7'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 7'h8 ),
    .din8_WIDTH( 16 ),
    .CASE9( 7'h9 ),
    .din9_WIDTH( 16 ),
    .CASE10( 7'hA ),
    .din10_WIDTH( 16 ),
    .CASE11( 7'hB ),
    .din11_WIDTH( 16 ),
    .CASE12( 7'hC ),
    .din12_WIDTH( 16 ),
    .CASE13( 7'hD ),
    .din13_WIDTH( 16 ),
    .CASE14( 7'hE ),
    .din14_WIDTH( 16 ),
    .CASE15( 7'hF ),
    .din15_WIDTH( 16 ),
    .CASE16( 7'h10 ),
    .din16_WIDTH( 16 ),
    .CASE17( 7'h11 ),
    .din17_WIDTH( 16 ),
    .CASE18( 7'h12 ),
    .din18_WIDTH( 16 ),
    .CASE19( 7'h13 ),
    .din19_WIDTH( 16 ),
    .CASE20( 7'h14 ),
    .din20_WIDTH( 16 ),
    .CASE21( 7'h15 ),
    .din21_WIDTH( 16 ),
    .CASE22( 7'h16 ),
    .din22_WIDTH( 16 ),
    .CASE23( 7'h17 ),
    .din23_WIDTH( 16 ),
    .CASE24( 7'h18 ),
    .din24_WIDTH( 16 ),
    .CASE25( 7'h19 ),
    .din25_WIDTH( 16 ),
    .CASE26( 7'h1A ),
    .din26_WIDTH( 16 ),
    .CASE27( 7'h1B ),
    .din27_WIDTH( 16 ),
    .CASE28( 7'h1C ),
    .din28_WIDTH( 16 ),
    .CASE29( 7'h1D ),
    .din29_WIDTH( 16 ),
    .CASE30( 7'h1E ),
    .din30_WIDTH( 16 ),
    .CASE31( 7'h1F ),
    .din31_WIDTH( 16 ),
    .CASE32( 7'h20 ),
    .din32_WIDTH( 16 ),
    .CASE33( 7'h21 ),
    .din33_WIDTH( 16 ),
    .CASE34( 7'h22 ),
    .din34_WIDTH( 16 ),
    .CASE35( 7'h23 ),
    .din35_WIDTH( 16 ),
    .CASE36( 7'h24 ),
    .din36_WIDTH( 16 ),
    .CASE37( 7'h25 ),
    .din37_WIDTH( 16 ),
    .CASE38( 7'h26 ),
    .din38_WIDTH( 16 ),
    .CASE39( 7'h27 ),
    .din39_WIDTH( 16 ),
    .CASE40( 7'h28 ),
    .din40_WIDTH( 16 ),
    .CASE41( 7'h29 ),
    .din41_WIDTH( 16 ),
    .CASE42( 7'h2A ),
    .din42_WIDTH( 16 ),
    .CASE43( 7'h2B ),
    .din43_WIDTH( 16 ),
    .CASE44( 7'h2C ),
    .din44_WIDTH( 16 ),
    .CASE45( 7'h2D ),
    .din45_WIDTH( 16 ),
    .CASE46( 7'h2E ),
    .din46_WIDTH( 16 ),
    .CASE47( 7'h2F ),
    .din47_WIDTH( 16 ),
    .CASE48( 7'h30 ),
    .din48_WIDTH( 16 ),
    .CASE49( 7'h31 ),
    .din49_WIDTH( 16 ),
    .CASE50( 7'h32 ),
    .din50_WIDTH( 16 ),
    .CASE51( 7'h33 ),
    .din51_WIDTH( 16 ),
    .CASE52( 7'h34 ),
    .din52_WIDTH( 16 ),
    .CASE53( 7'h35 ),
    .din53_WIDTH( 16 ),
    .CASE54( 7'h36 ),
    .din54_WIDTH( 16 ),
    .CASE55( 7'h37 ),
    .din55_WIDTH( 16 ),
    .CASE56( 7'h38 ),
    .din56_WIDTH( 16 ),
    .CASE57( 7'h39 ),
    .din57_WIDTH( 16 ),
    .CASE58( 7'h3A ),
    .din58_WIDTH( 16 ),
    .CASE59( 7'h3B ),
    .din59_WIDTH( 16 ),
    .CASE60( 7'h3C ),
    .din60_WIDTH( 16 ),
    .CASE61( 7'h3D ),
    .din61_WIDTH( 16 ),
    .CASE62( 7'h3E ),
    .din62_WIDTH( 16 ),
    .CASE63( 7'h3F ),
    .din63_WIDTH( 16 ),
    .CASE64( 7'h40 ),
    .din64_WIDTH( 16 ),
    .CASE65( 7'h41 ),
    .din65_WIDTH( 16 ),
    .CASE66( 7'h42 ),
    .din66_WIDTH( 16 ),
    .CASE67( 7'h43 ),
    .din67_WIDTH( 16 ),
    .CASE68( 7'h44 ),
    .din68_WIDTH( 16 ),
    .CASE69( 7'h45 ),
    .din69_WIDTH( 16 ),
    .CASE70( 7'h46 ),
    .din70_WIDTH( 16 ),
    .CASE71( 7'h47 ),
    .din71_WIDTH( 16 ),
    .CASE72( 7'h48 ),
    .din72_WIDTH( 16 ),
    .CASE73( 7'h49 ),
    .din73_WIDTH( 16 ),
    .CASE74( 7'h4A ),
    .din74_WIDTH( 16 ),
    .CASE75( 7'h4B ),
    .din75_WIDTH( 16 ),
    .CASE76( 7'h4C ),
    .din76_WIDTH( 16 ),
    .CASE77( 7'h4D ),
    .din77_WIDTH( 16 ),
    .CASE78( 7'h4E ),
    .din78_WIDTH( 16 ),
    .CASE79( 7'h4F ),
    .din79_WIDTH( 16 ),
    .CASE80( 7'h50 ),
    .din80_WIDTH( 16 ),
    .CASE81( 7'h51 ),
    .din81_WIDTH( 16 ),
    .CASE82( 7'h52 ),
    .din82_WIDTH( 16 ),
    .CASE83( 7'h53 ),
    .din83_WIDTH( 16 ),
    .CASE84( 7'h54 ),
    .din84_WIDTH( 16 ),
    .CASE85( 7'h55 ),
    .din85_WIDTH( 16 ),
    .CASE86( 7'h56 ),
    .din86_WIDTH( 16 ),
    .CASE87( 7'h57 ),
    .din87_WIDTH( 16 ),
    .CASE88( 7'h58 ),
    .din88_WIDTH( 16 ),
    .CASE89( 7'h59 ),
    .din89_WIDTH( 16 ),
    .CASE90( 7'h5A ),
    .din90_WIDTH( 16 ),
    .CASE91( 7'h5B ),
    .din91_WIDTH( 16 ),
    .CASE92( 7'h5C ),
    .din92_WIDTH( 16 ),
    .CASE93( 7'h5D ),
    .din93_WIDTH( 16 ),
    .CASE94( 7'h5E ),
    .din94_WIDTH( 16 ),
    .CASE95( 7'h5F ),
    .din95_WIDTH( 16 ),
    .CASE96( 7'h60 ),
    .din96_WIDTH( 16 ),
    .CASE97( 7'h61 ),
    .din97_WIDTH( 16 ),
    .CASE98( 7'h62 ),
    .din98_WIDTH( 16 ),
    .CASE99( 7'h63 ),
    .din99_WIDTH( 16 ),
    .CASE100( 7'h64 ),
    .din100_WIDTH( 16 ),
    .CASE101( 7'h65 ),
    .din101_WIDTH( 16 ),
    .CASE102( 7'h66 ),
    .din102_WIDTH( 16 ),
    .CASE103( 7'h67 ),
    .din103_WIDTH( 16 ),
    .CASE104( 7'h68 ),
    .din104_WIDTH( 16 ),
    .CASE105( 7'h69 ),
    .din105_WIDTH( 16 ),
    .CASE106( 7'h6A ),
    .din106_WIDTH( 16 ),
    .CASE107( 7'h6B ),
    .din107_WIDTH( 16 ),
    .CASE108( 7'h6C ),
    .din108_WIDTH( 16 ),
    .CASE109( 7'h6D ),
    .din109_WIDTH( 16 ),
    .CASE110( 7'h6E ),
    .din110_WIDTH( 16 ),
    .CASE111( 7'h6F ),
    .din111_WIDTH( 16 ),
    .CASE112( 7'h70 ),
    .din112_WIDTH( 16 ),
    .CASE113( 7'h71 ),
    .din113_WIDTH( 16 ),
    .CASE114( 7'h72 ),
    .din114_WIDTH( 16 ),
    .CASE115( 7'h73 ),
    .din115_WIDTH( 16 ),
    .CASE116( 7'h74 ),
    .din116_WIDTH( 16 ),
    .CASE117( 7'h75 ),
    .din117_WIDTH( 16 ),
    .CASE118( 7'h76 ),
    .din118_WIDTH( 16 ),
    .CASE119( 7'h77 ),
    .din119_WIDTH( 16 ),
    .CASE120( 7'h78 ),
    .din120_WIDTH( 16 ),
    .CASE121( 7'h79 ),
    .din121_WIDTH( 16 ),
    .CASE122( 7'h7A ),
    .din122_WIDTH( 16 ),
    .CASE123( 7'h7B ),
    .din123_WIDTH( 16 ),
    .CASE124( 7'h7C ),
    .din124_WIDTH( 16 ),
    .CASE125( 7'h7D ),
    .din125_WIDTH( 16 ),
    .CASE126( 7'h7E ),
    .din126_WIDTH( 16 ),
    .CASE127( 7'h7F ),
    .din127_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
sparsemux_257_7_16_1_1_U40(
    .din0(hidden1),
    .din1(hidden1_1),
    .din2(hidden1_2),
    .din3(hidden1_3),
    .din4(hidden1_4),
    .din5(hidden1_5),
    .din6(hidden1_6),
    .din7(hidden1_7),
    .din8(hidden1_8),
    .din9(hidden1_9),
    .din10(hidden1_10),
    .din11(hidden1_11),
    .din12(hidden1_12),
    .din13(hidden1_13),
    .din14(hidden1_14),
    .din15(hidden1_15),
    .din16(hidden1_16),
    .din17(hidden1_17),
    .din18(hidden1_18),
    .din19(hidden1_19),
    .din20(hidden1_20),
    .din21(hidden1_21),
    .din22(hidden1_22),
    .din23(hidden1_23),
    .din24(hidden1_24),
    .din25(hidden1_25),
    .din26(hidden1_26),
    .din27(hidden1_27),
    .din28(hidden1_28),
    .din29(hidden1_29),
    .din30(hidden1_30),
    .din31(hidden1_31),
    .din32(hidden1_32),
    .din33(hidden1_33),
    .din34(hidden1_34),
    .din35(hidden1_35),
    .din36(hidden1_36),
    .din37(hidden1_37),
    .din38(hidden1_38),
    .din39(hidden1_39),
    .din40(hidden1_40),
    .din41(hidden1_41),
    .din42(hidden1_42),
    .din43(hidden1_43),
    .din44(hidden1_44),
    .din45(hidden1_45),
    .din46(hidden1_46),
    .din47(hidden1_47),
    .din48(hidden1_48),
    .din49(hidden1_49),
    .din50(hidden1_50),
    .din51(hidden1_51),
    .din52(hidden1_52),
    .din53(hidden1_53),
    .din54(hidden1_54),
    .din55(hidden1_55),
    .din56(hidden1_56),
    .din57(hidden1_57),
    .din58(hidden1_58),
    .din59(hidden1_59),
    .din60(hidden1_60),
    .din61(hidden1_61),
    .din62(hidden1_62),
    .din63(hidden1_63),
    .din64(hidden1_64),
    .din65(hidden1_65),
    .din66(hidden1_66),
    .din67(hidden1_67),
    .din68(hidden1_68),
    .din69(hidden1_69),
    .din70(hidden1_70),
    .din71(hidden1_71),
    .din72(hidden1_72),
    .din73(hidden1_73),
    .din74(hidden1_74),
    .din75(hidden1_75),
    .din76(hidden1_76),
    .din77(hidden1_77),
    .din78(hidden1_78),
    .din79(hidden1_79),
    .din80(hidden1_80),
    .din81(hidden1_81),
    .din82(hidden1_82),
    .din83(hidden1_83),
    .din84(hidden1_84),
    .din85(hidden1_85),
    .din86(hidden1_86),
    .din87(hidden1_87),
    .din88(hidden1_88),
    .din89(hidden1_89),
    .din90(hidden1_90),
    .din91(hidden1_91),
    .din92(hidden1_92),
    .din93(hidden1_93),
    .din94(hidden1_94),
    .din95(hidden1_95),
    .din96(hidden1_96),
    .din97(hidden1_97),
    .din98(hidden1_98),
    .din99(hidden1_99),
    .din100(hidden1_100),
    .din101(hidden1_101),
    .din102(hidden1_102),
    .din103(hidden1_103),
    .din104(hidden1_104),
    .din105(hidden1_105),
    .din106(hidden1_106),
    .din107(hidden1_107),
    .din108(hidden1_108),
    .din109(hidden1_109),
    .din110(hidden1_110),
    .din111(hidden1_111),
    .din112(hidden1_112),
    .din113(hidden1_113),
    .din114(hidden1_114),
    .din115(hidden1_115),
    .din116(hidden1_116),
    .din117(hidden1_117),
    .din118(hidden1_118),
    .din119(hidden1_119),
    .din120(hidden1_120),
    .din121(hidden1_121),
    .din122(hidden1_122),
    .din123(hidden1_123),
    .din124(hidden1_124),
    .din125(hidden1_125),
    .din126(hidden1_126),
    .din127(hidden1_127),
    .def(tmp_22_fu_1467_p257),
    .sel(trunc_ln57_4_fu_1450_p1),
    .dout(tmp_22_fu_1467_p259)
);

(* dissolve_hierarchy = "yes" *) ecg_classify_trained_sparsemux_9_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_9_3_16_1_1_U41(
    .din0(16'd0),
    .din1(trunc_ln59_18_reg_2325_pp0_iter5_reg),
    .din2(select_ln59_2_reg_2341),
    .din3(select_ln59_3_reg_2346),
    .def(ref_tmp_i_i312_4_fu_2199_p9),
    .sel(ref_tmp_i_i312_4_fu_2199_p10),
    .dout(ref_tmp_i_i312_4_fu_2199_p11)
);

ecg_classify_trained_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_22_reg_2271_pp0_iter5_reg),
    .din1(ref_tmp_i_i312_4_fu_2199_p11),
    .din2(ap_sig_allocacmp_sum),
    .ce(1'b1),
    .dout(grp_fu_2239_p3)
);

ecg_classify_trained_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter8_stage0)) begin
            ap_enable_reg_pp0_iter9 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln57_fu_1438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_2_fu_614 <= add_ln57_fu_1444_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_2_fu_614 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_6_fu_610 <= sext_ln55_2_cast_fu_1421_p1;
        end else if ((ap_enable_reg_pp0_iter9 == 1'b1)) begin
            sum_6_fu_610 <= grp_fu_2239_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln59_1_reg_2336 <= and_ln59_1_fu_2128_p2;
        and_ln59_1_reg_2336_pp0_iter5_reg <= and_ln59_1_reg_2336;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        icmp_ln57_reg_2262_pp0_iter2_reg <= icmp_ln57_reg_2262_pp0_iter1_reg;
        icmp_ln57_reg_2262_pp0_iter3_reg <= icmp_ln57_reg_2262_pp0_iter2_reg;
        icmp_ln57_reg_2262_pp0_iter4_reg <= icmp_ln57_reg_2262_pp0_iter3_reg;
        icmp_ln57_reg_2262_pp0_iter5_reg <= icmp_ln57_reg_2262_pp0_iter4_reg;
        icmp_ln57_reg_2262_pp0_iter6_reg <= icmp_ln57_reg_2262_pp0_iter5_reg;
        icmp_ln57_reg_2262_pp0_iter7_reg <= icmp_ln57_reg_2262_pp0_iter6_reg;
        icmp_ln59_2_reg_2320 <= icmp_ln59_2_fu_2090_p2;
        icmp_ln59_2_reg_2320_pp0_iter5_reg <= icmp_ln59_2_reg_2320;
        icmp_ln59_9_reg_2331 <= icmp_ln59_9_fu_2110_p2;
        icmp_ln59_reg_2307 <= icmp_ln59_fu_2049_p2;
        icmp_ln59_reg_2307_pp0_iter5_reg <= icmp_ln59_reg_2307;
        select_ln59_1_reg_2313 <= select_ln59_1_fu_2082_p3;
        select_ln59_2_reg_2341 <= select_ln59_2_fu_2158_p3;
        select_ln59_3_reg_2346 <= select_ln59_3_fu_2174_p3;
        select_ln59_reg_2302 <= select_ln59_fu_2042_p3;
        tmp_22_reg_2271_pp0_iter2_reg <= tmp_22_reg_2271_pp0_iter1_reg;
        tmp_22_reg_2271_pp0_iter3_reg <= tmp_22_reg_2271_pp0_iter2_reg;
        tmp_22_reg_2271_pp0_iter4_reg <= tmp_22_reg_2271_pp0_iter3_reg;
        tmp_22_reg_2271_pp0_iter5_reg <= tmp_22_reg_2271_pp0_iter4_reg;
        tmp_reg_2286 <= bitcast_ln716_fu_1992_p1[32'd63];
        tmp_reg_2286_pp0_iter4_reg <= tmp_reg_2286;
        tmp_s_reg_2292 <= {{bitcast_ln716_fu_1992_p1[62:52]}};
        trunc_ln59_16_reg_2297 <= trunc_ln59_16_fu_2018_p1;
        trunc_ln59_18_reg_2325 <= trunc_ln59_18_fu_2096_p1;
        trunc_ln59_18_reg_2325_pp0_iter5_reg <= trunc_ln59_18_reg_2325;
        trunc_ln59_reg_2281 <= trunc_ln59_fu_1996_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        dense_1_weights_load_reg_2276 <= dense_1_weights_q0;
        icmp_ln57_reg_2262 <= icmp_ln57_fu_1438_p2;
        icmp_ln57_reg_2262_pp0_iter1_reg <= icmp_ln57_reg_2262;
        tmp_22_reg_2271 <= tmp_22_fu_1467_p259;
        tmp_22_reg_2271_pp0_iter1_reg <= tmp_22_reg_2271;
    end
end

always @ (*) begin
    if (((icmp_ln57_fu_1438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter8 == 1'b1) & (icmp_ln57_reg_2262_pp0_iter7_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter8_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter8_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j = 8'd0;
    end else begin
        ap_sig_allocacmp_j = j_2_fu_614;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        ap_sig_allocacmp_sum = grp_fu_2239_p3;
    end else begin
        ap_sig_allocacmp_sum = sum_6_fu_610;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dense_1_weights_ce0_local = 1'b1;
    end else begin
        dense_1_weights_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (icmp_ln57_reg_2262_pp0_iter7_reg == 1'd1))) begin
        sum_6_out_ap_vld = 1'b1;
    end else begin
        sum_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln57_fu_1444_p2 = (ap_sig_allocacmp_j + 8'd1);

assign add_ln59_1_fu_2070_p2 = ($signed(trunc_ln59_17_fu_2060_p1) + $signed(11'd2040));

assign add_ln_fu_1454_p3 = {{trunc_ln57_4_fu_1450_p1}, {zext_ln53_1}};

assign and_ln59_1_fu_2128_p2 = (xor_ln59_1_fu_2122_p2 & icmp_ln59_1_fu_2064_p2);

assign and_ln59_fu_2186_p2 = (xor_ln59_fu_2181_p2 & icmp_ln59_2_reg_2320_pp0_iter5_reg);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign ashr_ln59_fu_2142_p2 = $signed(select_ln59_reg_2302) >>> zext_ln59_2_fu_2139_p1;

assign bitcast_ln716_fu_1992_p1 = grp_fu_13213_p_dout0;

assign dense_1_weights_address0 = zext_ln59_1_fu_1462_p1;

assign dense_1_weights_ce0 = dense_1_weights_ce0_local;

assign grp_fu_13213_p_ce = 1'b1;

assign grp_fu_13213_p_din0 = dense_1_weights_load_reg_2276;

assign icmp_ln57_fu_1438_p2 = ((ap_sig_allocacmp_j == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln59_1_fu_2064_p2 = (($signed(sub_ln59_1_fu_2054_p2) > $signed(12'd8)) ? 1'b1 : 1'b0);

assign icmp_ln59_2_fu_2090_p2 = ((sub_ln59_1_fu_2054_p2 == 12'd8) ? 1'b1 : 1'b0);

assign icmp_ln59_3_fu_2134_p2 = ((select_ln59_1_reg_2313 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln59_9_fu_2110_p2 = ((tmp_21_fu_2100_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_2049_p2 = ((trunc_ln59_reg_2281 == 63'd0) ? 1'b1 : 1'b0);

assign or_ln59_fu_2116_p2 = (icmp_ln59_fu_2049_p2 | icmp_ln59_2_fu_2090_p2);

assign ref_tmp_i_i312_4_fu_2199_p10 = {{{icmp_ln59_reg_2307_pp0_iter5_reg}, {and_ln59_fu_2186_p2}}, {and_ln59_1_reg_2336_pp0_iter5_reg}};

assign ref_tmp_i_i312_4_fu_2199_p9 = 'bx;

assign select_ln59_1_fu_2082_p3 = ((icmp_ln59_1_fu_2064_p2[0:0] == 1'b1) ? add_ln59_1_fu_2070_p2 : sub_ln59_2_fu_2076_p2);

assign select_ln59_1cast_fu_2166_p1 = select_ln59_1_reg_2313;

assign select_ln59_2_fu_2158_p3 = ((icmp_ln59_3_fu_2134_p2[0:0] == 1'b1) ? trunc_ln59_19_fu_2147_p1 : select_ln59_9_fu_2151_p3);

assign select_ln59_3_fu_2174_p3 = ((icmp_ln59_9_reg_2331[0:0] == 1'b1) ? shl_ln59_fu_2169_p2 : 16'd0);

assign select_ln59_9_fu_2151_p3 = ((tmp_reg_2286_pp0_iter4_reg[0:0] == 1'b1) ? 16'd65535 : 16'd0);

assign select_ln59_fu_2042_p3 = ((tmp_reg_2286[0:0] == 1'b1) ? sub_ln59_fu_2036_p2 : zext_ln59_11_fu_2032_p1);

assign sext_ln55_2_cast_fu_1421_p1 = $signed(sext_ln55_2);

assign shl_ln59_fu_2169_p2 = trunc_ln59_18_reg_2325 << select_ln59_1cast_fu_2166_p1;

assign sub_ln59_1_fu_2054_p2 = (12'd1075 - zext_ln59_fu_2022_p1);

assign sub_ln59_2_fu_2076_p2 = (11'd8 - trunc_ln59_17_fu_2060_p1);

assign sub_ln59_fu_2036_p2 = (54'd0 - zext_ln59_11_fu_2032_p1);

assign sum_6_out = ap_sig_allocacmp_sum[23:0];

assign tmp_21_fu_2100_p4 = {{select_ln59_1_fu_2082_p3[10:4]}};

assign tmp_22_fu_1467_p257 = 'bx;

assign trunc_ln57_4_fu_1450_p1 = ap_sig_allocacmp_j[6:0];

assign trunc_ln59_16_fu_2018_p1 = bitcast_ln716_fu_1992_p1[51:0];

assign trunc_ln59_17_fu_2060_p1 = sub_ln59_1_fu_2054_p2[10:0];

assign trunc_ln59_18_fu_2096_p1 = select_ln59_fu_2042_p3[15:0];

assign trunc_ln59_19_fu_2147_p1 = ashr_ln59_fu_2142_p2[15:0];

assign trunc_ln59_fu_1996_p1 = bitcast_ln716_fu_1992_p1[62:0];

assign xor_ln59_1_fu_2122_p2 = (or_ln59_fu_2116_p2 ^ 1'd1);

assign xor_ln59_fu_2181_p2 = (icmp_ln59_reg_2307_pp0_iter5_reg ^ 1'd1);

assign zext_ln59_11_fu_2032_p1 = zext_ln59_4_cast_fu_2025_p3;

assign zext_ln59_1_fu_1462_p1 = add_ln_fu_1454_p3;

assign zext_ln59_2_fu_2139_p1 = select_ln59_1_reg_2313;

assign zext_ln59_4_cast_fu_2025_p3 = {{1'd1}, {trunc_ln59_16_reg_2297}};

assign zext_ln59_fu_2022_p1 = tmp_s_reg_2292;

endmodule //ecg_classify_trained_ecg_classify_trained_Pipeline_VITIS_LOOP_57_4
