// ==============================================================
// Generated by Vitis HLS v2024.1.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ecg_classify_trained_ecg_classify_trained_Pipeline_VITIS_LOOP_88_812 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hidden3,
        hidden3_1,
        hidden3_2,
        hidden3_3,
        hidden3_4,
        hidden3_5,
        hidden3_6,
        hidden3_7,
        hidden3_8,
        hidden3_9,
        hidden3_10,
        hidden3_11,
        hidden3_12,
        hidden3_13,
        hidden3_14,
        hidden3_15,
        hidden3_16,
        hidden3_17,
        hidden3_18,
        hidden3_19,
        hidden3_20,
        hidden3_21,
        hidden3_22,
        hidden3_23,
        hidden3_24,
        hidden3_25,
        hidden3_26,
        hidden3_27,
        hidden3_28,
        hidden3_29,
        hidden3_30,
        hidden3_31,
        sum_17_out,
        sum_17_out_ap_vld,
        dense_3_weights_address0,
        dense_3_weights_ce0,
        dense_3_weights_q0,
        grp_fu_13213_p_din0,
        grp_fu_13213_p_dout0,
        grp_fu_13213_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] hidden3;
input  [15:0] hidden3_1;
input  [15:0] hidden3_2;
input  [15:0] hidden3_3;
input  [15:0] hidden3_4;
input  [15:0] hidden3_5;
input  [15:0] hidden3_6;
input  [15:0] hidden3_7;
input  [15:0] hidden3_8;
input  [15:0] hidden3_9;
input  [15:0] hidden3_10;
input  [15:0] hidden3_11;
input  [15:0] hidden3_12;
input  [15:0] hidden3_13;
input  [15:0] hidden3_14;
input  [15:0] hidden3_15;
input  [15:0] hidden3_16;
input  [15:0] hidden3_17;
input  [15:0] hidden3_18;
input  [15:0] hidden3_19;
input  [15:0] hidden3_20;
input  [15:0] hidden3_21;
input  [15:0] hidden3_22;
input  [15:0] hidden3_23;
input  [15:0] hidden3_24;
input  [15:0] hidden3_25;
input  [15:0] hidden3_26;
input  [15:0] hidden3_27;
input  [15:0] hidden3_28;
input  [15:0] hidden3_29;
input  [15:0] hidden3_30;
input  [15:0] hidden3_31;
output  [23:0] sum_17_out;
output   sum_17_out_ap_vld;
output  [7:0] dense_3_weights_address0;
output   dense_3_weights_ce0;
input  [31:0] dense_3_weights_q0;
output  [31:0] grp_fu_13213_p_din0;
input  [63:0] grp_fu_13213_p_dout0;
output   grp_fu_13213_p_ce;

reg ap_idle;
reg sum_17_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln88_fu_464_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln88_reg_927;
reg   [0:0] icmp_ln88_reg_927_pp0_iter1_reg;
reg   [0:0] icmp_ln88_reg_927_pp0_iter2_reg;
reg   [0:0] icmp_ln88_reg_927_pp0_iter3_reg;
reg   [0:0] icmp_ln88_reg_927_pp0_iter4_reg;
reg   [0:0] icmp_ln88_reg_927_pp0_iter5_reg;
reg   [0:0] icmp_ln88_reg_927_pp0_iter6_reg;
reg   [0:0] icmp_ln88_reg_927_pp0_iter7_reg;
reg   [0:0] icmp_ln88_reg_927_pp0_iter8_reg;
wire   [7:0] add_ln90_fu_506_p2;
reg   [7:0] add_ln90_reg_931;
wire   [15:0] tmp_7_fu_512_p67;
reg   [15:0] tmp_7_reg_936;
reg   [15:0] tmp_7_reg_936_pp0_iter1_reg;
reg   [15:0] tmp_7_reg_936_pp0_iter2_reg;
reg   [15:0] tmp_7_reg_936_pp0_iter3_reg;
reg   [15:0] tmp_7_reg_936_pp0_iter4_reg;
reg   [15:0] tmp_7_reg_936_pp0_iter5_reg;
reg  signed [15:0] tmp_7_reg_936_pp0_iter6_reg;
reg   [31:0] dense_3_weights_load_reg_946;
wire   [62:0] trunc_ln90_fu_661_p1;
reg   [62:0] trunc_ln90_reg_951;
reg   [0:0] tmp_5_reg_956;
reg   [0:0] tmp_5_reg_956_pp0_iter5_reg;
reg   [10:0] tmp_s_reg_962;
wire   [51:0] trunc_ln90_11_fu_683_p1;
reg   [51:0] trunc_ln90_11_reg_967;
wire   [53:0] select_ln90_fu_707_p3;
reg   [53:0] select_ln90_reg_972;
wire   [0:0] icmp_ln90_fu_714_p2;
reg   [0:0] icmp_ln90_reg_977;
reg   [0:0] icmp_ln90_reg_977_pp0_iter6_reg;
wire   [10:0] select_ln90_9_fu_747_p3;
reg   [10:0] select_ln90_9_reg_983;
wire   [0:0] icmp_ln90_10_fu_755_p2;
reg   [0:0] icmp_ln90_10_reg_990;
reg   [0:0] icmp_ln90_10_reg_990_pp0_iter6_reg;
wire   [15:0] trunc_ln90_13_fu_761_p1;
reg   [15:0] trunc_ln90_13_reg_995;
reg   [15:0] trunc_ln90_13_reg_995_pp0_iter6_reg;
wire   [0:0] icmp_ln90_12_fu_775_p2;
reg   [0:0] icmp_ln90_12_reg_1001;
wire   [0:0] and_ln90_3_fu_793_p2;
reg   [0:0] and_ln90_3_reg_1006;
reg   [0:0] and_ln90_3_reg_1006_pp0_iter6_reg;
wire   [15:0] select_ln90_11_fu_823_p3;
reg   [15:0] select_ln90_11_reg_1011;
wire   [15:0] select_ln90_12_fu_839_p3;
reg   [15:0] select_ln90_12_reg_1016;
reg    ap_condition_exit_pp0_iter9_stage0;
wire   [63:0] zext_ln90_11_fu_653_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] sum_fu_228;
wire   [31:0] grp_fu_904_p3;
reg   [31:0] ap_sig_allocacmp_sum_5;
wire    ap_loop_init;
reg   [5:0] j_fu_232;
wire   [5:0] add_ln88_fu_470_p2;
reg   [5:0] ap_sig_allocacmp_j_3;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
wire    ap_block_pp0_stage0_01001;
reg    dense_3_weights_ce0_local;
wire   [4:0] trunc_ln88_3_fu_476_p1;
wire   [6:0] tmp_fu_488_p3;
wire   [7:0] p_shl_fu_480_p3;
wire   [7:0] zext_ln90_fu_496_p1;
wire   [7:0] sub_ln90_fu_500_p2;
wire   [15:0] tmp_7_fu_512_p65;
wire   [63:0] bitcast_ln716_fu_657_p1;
wire   [52:0] zext_ln90_25_cast_fu_690_p3;
wire   [53:0] zext_ln90_12_fu_697_p1;
wire   [53:0] sub_ln90_7_fu_701_p2;
wire   [11:0] zext_ln90_8_fu_687_p1;
wire   [11:0] sub_ln90_8_fu_719_p2;
wire   [10:0] trunc_ln90_12_fu_725_p1;
wire   [0:0] icmp_ln90_9_fu_729_p2;
wire   [10:0] add_ln90_5_fu_735_p2;
wire   [10:0] sub_ln90_9_fu_741_p2;
wire   [6:0] tmp_6_fu_765_p4;
wire   [0:0] or_ln90_fu_781_p2;
wire   [0:0] xor_ln90_3_fu_787_p2;
wire   [53:0] zext_ln90_13_fu_804_p1;
wire   [53:0] ashr_ln90_fu_807_p2;
wire   [0:0] icmp_ln90_11_fu_799_p2;
wire   [15:0] trunc_ln90_14_fu_812_p1;
wire   [15:0] select_ln90_10_fu_816_p3;
wire   [15:0] select_ln90_9cast_fu_831_p1;
wire   [15:0] shl_ln90_fu_834_p2;
wire   [0:0] xor_ln90_fu_846_p2;
wire   [0:0] and_ln90_fu_851_p2;
wire   [15:0] ref_tmp_i_i30_1_fu_864_p9;
wire   [2:0] ref_tmp_i_i30_1_fu_864_p10;
wire  signed [15:0] ref_tmp_i_i30_1_fu_864_p11;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [4:0] tmp_7_fu_512_p1;
wire   [4:0] tmp_7_fu_512_p3;
wire   [4:0] tmp_7_fu_512_p5;
wire   [4:0] tmp_7_fu_512_p7;
wire   [4:0] tmp_7_fu_512_p9;
wire   [4:0] tmp_7_fu_512_p11;
wire   [4:0] tmp_7_fu_512_p13;
wire   [4:0] tmp_7_fu_512_p15;
wire   [4:0] tmp_7_fu_512_p17;
wire   [4:0] tmp_7_fu_512_p19;
wire   [4:0] tmp_7_fu_512_p21;
wire   [4:0] tmp_7_fu_512_p23;
wire   [4:0] tmp_7_fu_512_p25;
wire   [4:0] tmp_7_fu_512_p27;
wire   [4:0] tmp_7_fu_512_p29;
wire   [4:0] tmp_7_fu_512_p31;
wire  signed [4:0] tmp_7_fu_512_p33;
wire  signed [4:0] tmp_7_fu_512_p35;
wire  signed [4:0] tmp_7_fu_512_p37;
wire  signed [4:0] tmp_7_fu_512_p39;
wire  signed [4:0] tmp_7_fu_512_p41;
wire  signed [4:0] tmp_7_fu_512_p43;
wire  signed [4:0] tmp_7_fu_512_p45;
wire  signed [4:0] tmp_7_fu_512_p47;
wire  signed [4:0] tmp_7_fu_512_p49;
wire  signed [4:0] tmp_7_fu_512_p51;
wire  signed [4:0] tmp_7_fu_512_p53;
wire  signed [4:0] tmp_7_fu_512_p55;
wire  signed [4:0] tmp_7_fu_512_p57;
wire  signed [4:0] tmp_7_fu_512_p59;
wire  signed [4:0] tmp_7_fu_512_p61;
wire  signed [4:0] tmp_7_fu_512_p63;
wire  signed [2:0] ref_tmp_i_i30_1_fu_864_p1;
wire   [2:0] ref_tmp_i_i30_1_fu_864_p3;
wire   [2:0] ref_tmp_i_i30_1_fu_864_p5;
wire   [2:0] ref_tmp_i_i30_1_fu_864_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 sum_fu_228 = 32'd0;
#0 j_fu_232 = 6'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) ecg_classify_trained_sparsemux_65_5_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 16 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 16 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 16 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 16 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 16 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 16 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 16 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 16 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 16 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 16 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 16 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 16 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 16 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 16 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 16 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 16 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 16 ),
    .CASE25( 5'h19 ),
    .din25_WIDTH( 16 ),
    .CASE26( 5'h1A ),
    .din26_WIDTH( 16 ),
    .CASE27( 5'h1B ),
    .din27_WIDTH( 16 ),
    .CASE28( 5'h1C ),
    .din28_WIDTH( 16 ),
    .CASE29( 5'h1D ),
    .din29_WIDTH( 16 ),
    .CASE30( 5'h1E ),
    .din30_WIDTH( 16 ),
    .CASE31( 5'h1F ),
    .din31_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 16 ))
sparsemux_65_5_16_1_1_U989(
    .din0(hidden3),
    .din1(hidden3_1),
    .din2(hidden3_2),
    .din3(hidden3_3),
    .din4(hidden3_4),
    .din5(hidden3_5),
    .din6(hidden3_6),
    .din7(hidden3_7),
    .din8(hidden3_8),
    .din9(hidden3_9),
    .din10(hidden3_10),
    .din11(hidden3_11),
    .din12(hidden3_12),
    .din13(hidden3_13),
    .din14(hidden3_14),
    .din15(hidden3_15),
    .din16(hidden3_16),
    .din17(hidden3_17),
    .din18(hidden3_18),
    .din19(hidden3_19),
    .din20(hidden3_20),
    .din21(hidden3_21),
    .din22(hidden3_22),
    .din23(hidden3_23),
    .din24(hidden3_24),
    .din25(hidden3_25),
    .din26(hidden3_26),
    .din27(hidden3_27),
    .din28(hidden3_28),
    .din29(hidden3_29),
    .din30(hidden3_30),
    .din31(hidden3_31),
    .def(tmp_7_fu_512_p65),
    .sel(trunc_ln88_3_fu_476_p1),
    .dout(tmp_7_fu_512_p67)
);

(* dissolve_hierarchy = "yes" *) ecg_classify_trained_sparsemux_9_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_9_3_16_1_1_U990(
    .din0(16'd0),
    .din1(trunc_ln90_13_reg_995_pp0_iter6_reg),
    .din2(select_ln90_11_reg_1011),
    .din3(select_ln90_12_reg_1016),
    .def(ref_tmp_i_i30_1_fu_864_p9),
    .sel(ref_tmp_i_i30_1_fu_864_p10),
    .dout(ref_tmp_i_i30_1_fu_864_p11)
);

ecg_classify_trained_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U991(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_7_reg_936_pp0_iter6_reg),
    .din1(ref_tmp_i_i30_1_fu_864_p11),
    .din2(ap_sig_allocacmp_sum_5),
    .ce(1'b1),
    .dout(grp_fu_904_p3)
);

ecg_classify_trained_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter9_stage0)) begin
            ap_enable_reg_pp0_iter10 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln88_fu_464_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_232 <= add_ln88_fu_470_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_232 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_fu_228 <= 32'd15104;
        end else if ((ap_enable_reg_pp0_iter10 == 1'b1)) begin
            sum_fu_228 <= grp_fu_904_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln90_reg_931[7 : 1] <= add_ln90_fu_506_p2[7 : 1];
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln88_reg_927 <= icmp_ln88_fu_464_p2;
        icmp_ln88_reg_927_pp0_iter1_reg <= icmp_ln88_reg_927;
        tmp_7_reg_936 <= tmp_7_fu_512_p67;
        tmp_7_reg_936_pp0_iter1_reg <= tmp_7_reg_936;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln90_3_reg_1006 <= and_ln90_3_fu_793_p2;
        and_ln90_3_reg_1006_pp0_iter6_reg <= and_ln90_3_reg_1006;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        dense_3_weights_load_reg_946 <= dense_3_weights_q0;
        icmp_ln88_reg_927_pp0_iter2_reg <= icmp_ln88_reg_927_pp0_iter1_reg;
        icmp_ln88_reg_927_pp0_iter3_reg <= icmp_ln88_reg_927_pp0_iter2_reg;
        icmp_ln88_reg_927_pp0_iter4_reg <= icmp_ln88_reg_927_pp0_iter3_reg;
        icmp_ln88_reg_927_pp0_iter5_reg <= icmp_ln88_reg_927_pp0_iter4_reg;
        icmp_ln88_reg_927_pp0_iter6_reg <= icmp_ln88_reg_927_pp0_iter5_reg;
        icmp_ln88_reg_927_pp0_iter7_reg <= icmp_ln88_reg_927_pp0_iter6_reg;
        icmp_ln88_reg_927_pp0_iter8_reg <= icmp_ln88_reg_927_pp0_iter7_reg;
        icmp_ln90_10_reg_990 <= icmp_ln90_10_fu_755_p2;
        icmp_ln90_10_reg_990_pp0_iter6_reg <= icmp_ln90_10_reg_990;
        icmp_ln90_12_reg_1001 <= icmp_ln90_12_fu_775_p2;
        icmp_ln90_reg_977 <= icmp_ln90_fu_714_p2;
        icmp_ln90_reg_977_pp0_iter6_reg <= icmp_ln90_reg_977;
        select_ln90_11_reg_1011 <= select_ln90_11_fu_823_p3;
        select_ln90_12_reg_1016 <= select_ln90_12_fu_839_p3;
        select_ln90_9_reg_983 <= select_ln90_9_fu_747_p3;
        select_ln90_reg_972 <= select_ln90_fu_707_p3;
        tmp_5_reg_956 <= bitcast_ln716_fu_657_p1[32'd63];
        tmp_5_reg_956_pp0_iter5_reg <= tmp_5_reg_956;
        tmp_7_reg_936_pp0_iter2_reg <= tmp_7_reg_936_pp0_iter1_reg;
        tmp_7_reg_936_pp0_iter3_reg <= tmp_7_reg_936_pp0_iter2_reg;
        tmp_7_reg_936_pp0_iter4_reg <= tmp_7_reg_936_pp0_iter3_reg;
        tmp_7_reg_936_pp0_iter5_reg <= tmp_7_reg_936_pp0_iter4_reg;
        tmp_7_reg_936_pp0_iter6_reg <= tmp_7_reg_936_pp0_iter5_reg;
        tmp_s_reg_962 <= {{bitcast_ln716_fu_657_p1[62:52]}};
        trunc_ln90_11_reg_967 <= trunc_ln90_11_fu_683_p1;
        trunc_ln90_13_reg_995 <= trunc_ln90_13_fu_761_p1;
        trunc_ln90_13_reg_995_pp0_iter6_reg <= trunc_ln90_13_reg_995;
        trunc_ln90_reg_951 <= trunc_ln90_fu_661_p1;
    end
end

always @ (*) begin
    if (((icmp_ln88_fu_464_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter9 == 1'b1) & (icmp_ln88_reg_927_pp0_iter8_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter9_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter9_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_3 = 6'd0;
    end else begin
        ap_sig_allocacmp_j_3 = j_fu_232;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        ap_sig_allocacmp_sum_5 = grp_fu_904_p3;
    end else begin
        ap_sig_allocacmp_sum_5 = sum_fu_228;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dense_3_weights_ce0_local = 1'b1;
    end else begin
        dense_3_weights_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (icmp_ln88_reg_927_pp0_iter8_reg == 1'd1))) begin
        sum_17_out_ap_vld = 1'b1;
    end else begin
        sum_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln88_fu_470_p2 = (ap_sig_allocacmp_j_3 + 6'd1);

assign add_ln90_5_fu_735_p2 = ($signed(trunc_ln90_12_fu_725_p1) + $signed(11'd2040));

assign add_ln90_fu_506_p2 = (sub_ln90_fu_500_p2 + 8'd3);

assign and_ln90_3_fu_793_p2 = (xor_ln90_3_fu_787_p2 & icmp_ln90_9_fu_729_p2);

assign and_ln90_fu_851_p2 = (xor_ln90_fu_846_p2 & icmp_ln90_10_reg_990_pp0_iter6_reg);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign ashr_ln90_fu_807_p2 = $signed(select_ln90_reg_972) >>> zext_ln90_13_fu_804_p1;

assign bitcast_ln716_fu_657_p1 = grp_fu_13213_p_dout0;

assign dense_3_weights_address0 = zext_ln90_11_fu_653_p1;

assign dense_3_weights_ce0 = dense_3_weights_ce0_local;

assign grp_fu_13213_p_ce = 1'b1;

assign grp_fu_13213_p_din0 = dense_3_weights_load_reg_946;

assign icmp_ln88_fu_464_p2 = ((ap_sig_allocacmp_j_3 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln90_10_fu_755_p2 = ((sub_ln90_8_fu_719_p2 == 12'd8) ? 1'b1 : 1'b0);

assign icmp_ln90_11_fu_799_p2 = ((select_ln90_9_reg_983 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln90_12_fu_775_p2 = ((tmp_6_fu_765_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln90_9_fu_729_p2 = (($signed(sub_ln90_8_fu_719_p2) > $signed(12'd8)) ? 1'b1 : 1'b0);

assign icmp_ln90_fu_714_p2 = ((trunc_ln90_reg_951 == 63'd0) ? 1'b1 : 1'b0);

assign or_ln90_fu_781_p2 = (icmp_ln90_fu_714_p2 | icmp_ln90_10_fu_755_p2);

assign p_shl_fu_480_p3 = {{trunc_ln88_3_fu_476_p1}, {3'd0}};

assign ref_tmp_i_i30_1_fu_864_p10 = {{{icmp_ln90_reg_977_pp0_iter6_reg}, {and_ln90_fu_851_p2}}, {and_ln90_3_reg_1006_pp0_iter6_reg}};

assign ref_tmp_i_i30_1_fu_864_p9 = 'bx;

assign select_ln90_10_fu_816_p3 = ((tmp_5_reg_956_pp0_iter5_reg[0:0] == 1'b1) ? 16'd65535 : 16'd0);

assign select_ln90_11_fu_823_p3 = ((icmp_ln90_11_fu_799_p2[0:0] == 1'b1) ? trunc_ln90_14_fu_812_p1 : select_ln90_10_fu_816_p3);

assign select_ln90_12_fu_839_p3 = ((icmp_ln90_12_reg_1001[0:0] == 1'b1) ? shl_ln90_fu_834_p2 : 16'd0);

assign select_ln90_9_fu_747_p3 = ((icmp_ln90_9_fu_729_p2[0:0] == 1'b1) ? add_ln90_5_fu_735_p2 : sub_ln90_9_fu_741_p2);

assign select_ln90_9cast_fu_831_p1 = select_ln90_9_reg_983;

assign select_ln90_fu_707_p3 = ((tmp_5_reg_956[0:0] == 1'b1) ? sub_ln90_7_fu_701_p2 : zext_ln90_12_fu_697_p1);

assign shl_ln90_fu_834_p2 = trunc_ln90_13_reg_995 << select_ln90_9cast_fu_831_p1;

assign sub_ln90_7_fu_701_p2 = (54'd0 - zext_ln90_12_fu_697_p1);

assign sub_ln90_8_fu_719_p2 = (12'd1075 - zext_ln90_8_fu_687_p1);

assign sub_ln90_9_fu_741_p2 = (11'd8 - trunc_ln90_12_fu_725_p1);

assign sub_ln90_fu_500_p2 = (p_shl_fu_480_p3 - zext_ln90_fu_496_p1);

assign sum_17_out = ap_sig_allocacmp_sum_5[23:0];

assign tmp_6_fu_765_p4 = {{select_ln90_9_fu_747_p3[10:4]}};

assign tmp_7_fu_512_p65 = 'bx;

assign tmp_fu_488_p3 = {{ap_sig_allocacmp_j_3}, {1'd0}};

assign trunc_ln88_3_fu_476_p1 = ap_sig_allocacmp_j_3[4:0];

assign trunc_ln90_11_fu_683_p1 = bitcast_ln716_fu_657_p1[51:0];

assign trunc_ln90_12_fu_725_p1 = sub_ln90_8_fu_719_p2[10:0];

assign trunc_ln90_13_fu_761_p1 = select_ln90_fu_707_p3[15:0];

assign trunc_ln90_14_fu_812_p1 = ashr_ln90_fu_807_p2[15:0];

assign trunc_ln90_fu_661_p1 = bitcast_ln716_fu_657_p1[62:0];

assign xor_ln90_3_fu_787_p2 = (or_ln90_fu_781_p2 ^ 1'd1);

assign xor_ln90_fu_846_p2 = (icmp_ln90_reg_977_pp0_iter6_reg ^ 1'd1);

assign zext_ln90_11_fu_653_p1 = add_ln90_reg_931;

assign zext_ln90_12_fu_697_p1 = zext_ln90_25_cast_fu_690_p3;

assign zext_ln90_13_fu_804_p1 = select_ln90_9_reg_983;

assign zext_ln90_25_cast_fu_690_p3 = {{1'd1}, {trunc_ln90_11_reg_967}};

assign zext_ln90_8_fu_687_p1 = tmp_s_reg_962;

assign zext_ln90_fu_496_p1 = tmp_fu_488_p3;

always @ (posedge ap_clk) begin
    add_ln90_reg_931[0] <= 1'b1;
end

endmodule //ecg_classify_trained_ecg_classify_trained_Pipeline_VITIS_LOOP_88_812
